import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import {LayoutDashboard,Users,GraduationCap,BookOpen,CalendarDays,ClipboardCheck,FileText,Wallet,Bus,MessageCircle,Bell,Settings,LogOut,Menu,Clock,CheckCircle2,Plus,Search,ChevronRight,UserRound,School,ShieldCheck,Trash2,Edit3,Download,Send,Target,Library,RefreshCw,AlertTriangle} from "lucide-react";
import "./styles.css";

const accounts={
 admin:{email:"admin@school.demo",password:"admin123",name:"School Admin",role:"Admin"},
 teacher:{email:"priya@school.demo",password:"teacher123",name:"Priya Sharma",role:"Teacher"},
};
const initialStudents=[
 {name:"Aarav Kumar",className:"Grade 3-A",roll:"01",parent:"Kumar Raj",attendance:"96%"},
 {name:"Ananya Priya",className:"Grade 3-A",roll:"02",parent:"Priya Devi",attendance:"98%"},
 {name:"Dhruv Anand",className:"Grade 4-B",roll:"07",parent:"Anand S",attendance:"91%"},
 {name:"Ishita Rao",className:"Grade 5-A",roll:"11",parent:"Rao Meena",attendance:"94%"},
 {name:"Vihaan Raj",className:"Grade 2-B",roll:"05",parent:"Rajesh Kumar",attendance:"89%"}
];
const initialTeachers=[{name:"Priya Sharma",subject:"Mathematics",classes:"Grade 3-A / 4-B"},{name:"Meena Joseph",subject:"English",classes:"Grade 2-A / 3-A"},{name:"Arun Kumar",subject:"EVS",classes:"Grade 4-B / 5-A"},{name:"Kavitha R",subject:"Tamil",classes:"Grade 1-A / 2-B"},{name:"Nisha Kapoor",subject:"Hindi",classes:"Grade 1-A / 3-A"},{name:"Vijay Kumar",subject:"Computer Science",classes:"Grade 3-A / 5-A"},{name:"Anitha Raj",subject:"Yoga",classes:"Grade 1-A / 5-B"},{name:"Ramesh S",subject:"Physical Education",classes:"Grade 2-B / 4-B"},{name:"Divya Menon",subject:"Art & Craft / Music",classes:"Grade 2-B / 5-A"}];
const teacherAccounts=initialTeachers.map(t=>({name:t.name,email:t.name.toLowerCase().replaceAll(" ",".")+"@school.demo",password:"teacher123",role:"Teacher"}));
const parentAccounts=initialStudents.map((st,i)=>({name:st.parent,email:i===1?"parent@school.demo":st.parent.toLowerCase().replaceAll(" ",".")+"@school.demo",password:"parent123",role:"Parent",child:st.name,className:st.className,roll:st.roll}));
const portalAccounts={admin:accounts.admin,teacher:accounts.teacher,parent:parentAccounts[1]||parentAccounts[0]};
const primarySubjects=["Tamil","English","Mathematics","EVS","Hindi","Computer Science","General Knowledge","Art & Craft","Music","Yoga","Physical Education","Moral Science"];
const initialClasses=["Grade 1-A","Grade 2-B","Grade 3-A","Grade 4-B","Grade 5-A","Grade 5-B"];
const initialHomework=[
 {subject:"Mathematics",title:"Multiplication worksheet – Page 24",due:"Today",completed:false},
 {subject:"English",title:"Read Story 6 and write 5 new words",due:"Tomorrow",completed:false},
 {subject:"EVS",title:"Parts of a Plant drawing",due:"Friday",completed:false},
 {subject:"Hindi",title:"Write 5 simple Hindi words",due:"Monday",completed:false},
 {subject:"Computer Science",title:"Draw and label the parts of a computer",due:"Wednesday",completed:false}
];
const initialLibrary=[
 {id:1,title:"Panchatantra Stories",author:"Children's Classics",category:"Story",ageGroup:"6–10 Years",total:5,available:5,issuedTo:"",due:""},
 {id:2,title:"Akbar and Birbal Stories",author:"Indian Folktales",category:"Story",ageGroup:"7–11 Years",total:4,available:4,issuedTo:"",due:""},
 {id:3,title:"Fun with Numbers",author:"Bright Future Press",category:"Mathematics",ageGroup:"6–10 Years",total:5,available:5,issuedTo:"",due:""},
 {id:4,title:"Amazing Animals",author:"School Library",category:"EVS",ageGroup:"6–10 Years",total:4,available:4,issuedTo:"",due:""},
 {id:5,title:"Plants Around Us",author:"School Library",category:"EVS",ageGroup:"7–11 Years",total:4,available:4,issuedTo:"",due:""},
 {id:6,title:"Good Habits for Kids",author:"Bright Future Press",category:"Life Skills",ageGroup:"5–9 Years",total:4,available:4,issuedTo:"",due:""},
 {id:7,title:"Tamil Sirukathaigal for Kids",author:"Tamil Children’s Collection",category:"Tamil",ageGroup:"6–11 Years",total:4,available:4,issuedTo:"",due:""},
 {id:8,title:"Draw, Colour & Create",author:"Creative Kids Studio",category:"Activity",ageGroup:"5–10 Years",total:4,available:4,issuedTo:"",due:""}
];
const initialNotices=[
 {icon:"📢",title:"Parent Meeting",date:"Saturday · 10:00 AM",body:"All parents are invited for the monthly progress meeting."},
 {icon:"🏆",title:"Inter-house Quiz",date:"September 15",body:"Students from Grades 3–5 can register with their class teacher."},
 {icon:"🎉",title:"Teachers' Day Celebration",date:"September 5",body:"Special assembly and student activities."},
 {icon:"🚌",title:"Transport Update",date:"Tomorrow",body:"Route 4 will depart 10 minutes earlier."}
];
const defaultTT=[
 ["Monday","09:00 AM","Mathematics","Priya Sharma"],["Monday","10:00 AM","English","Meena Joseph"],["Monday","11:15 AM","EVS","Arun Kumar"],["Monday","12:15 PM","Hindi","Nisha Kapoor"],
 ["Tuesday","09:00 AM","Tamil","Kavitha R"],["Tuesday","10:00 AM","Computer Science","Vijay Kumar"],["Tuesday","11:15 AM","Yoga","Anitha Raj"],["Tuesday","12:15 PM","Art & Craft","Divya Menon"],
 ["Wednesday","09:00 AM","Mathematics","Priya Sharma"],["Wednesday","10:00 AM","General Knowledge","Meena Joseph"],["Wednesday","11:15 AM","Physical Education","Ramesh S"],["Wednesday","12:15 PM","Music","Divya Menon"],
 ["Thursday","09:00 AM","English","Meena Joseph"],["Thursday","10:00 AM","EVS","Arun Kumar"],["Thursday","11:15 AM","Hindi","Nisha Kapoor"],["Thursday","12:15 PM","Moral Science","Kavitha R"],
 ["Friday","09:00 AM","Mathematics","Priya Sharma"],["Friday","10:00 AM","Tamil","Kavitha R"],["Friday","11:15 AM","Computer Science","Vijay Kumar"],["Friday","12:15 PM","Yoga","Anitha Raj"]
];

const marks=["Mathematics","English","EVS","Tamil","Hindi","Computer Science","General Knowledge","Art & Craft","Music","Yoga","Physical Education","Moral Science"].map((s,i)=>({subject:s,score:[86,91,88,94,89,92,87,95,90,93,88,96][i]}));
const initialChatMessages=[];
const initialSubstitutions=[];
const initialAvailabilityRequests=[];
const navs={
 Admin:[["Dashboard","Dashboard",LayoutDashboard],["Students","Students",Users],["Teachers & Staff","Teachers",GraduationCap],["Staff Requests","Staff Requests",AlertTriangle],["Staff Substitution","Staff Substitution",RefreshCw],["Classes & Subjects","Classes",School],["Timetable & Periods","Timetable",Clock],["Attendance","Attendance",ClipboardCheck],["Exams & Marks","Exams & Marks",FileText],["Homework","Homework",BookOpen],["Library","Library",Library],["Fees & Payments","Fees",Wallet],["Transport","Transport",Bus],["School Calendar","Calendar",CalendarDays],["Notices & Communication","Notices",Bell],["User Management","User Management",ShieldCheck],["Reports","Reports",FileText],["Progress Tracker","Progress Tracker",Target],["Settings","Settings",Settings]],
 Teacher:[["Dashboard","Dashboard",LayoutDashboard],["My Timetable","My Timetable",Clock],["My Students","My Students",Users],["Attendance","Attendance",ClipboardCheck],["Homework & Classwork","Homework",BookOpen],["Library","Library",Library],["Enter Marks","Enter Marks",FileText],["Notices","Notices",Bell],["Parent Messages","Parent Messages",MessageCircle],["Report Unavailability","Report Unavailability",AlertTriangle],["Substitution Duty","Substitution Duty",RefreshCw],["Progress Tracker","Progress Tracker",Target],["Leave Request","Leave Request",CalendarDays],["My Profile","My Profile",UserRound]],
 Parent:[["Dashboard","Dashboard",LayoutDashboard],["My Child","My Child",Users],["Child Attendance","Attendance",ClipboardCheck],["Class Timetable","Timetable",Clock],["Homework","Homework",BookOpen],["Library","Library",Library],["Marks / Report Card","Marks / Report Card",FileText],["Fees & Payment","Fees & Payment",Wallet],["School Calendar","Calendar",CalendarDays],["Notices","Notices",Bell],["Teacher Chat","Teacher Chat",MessageCircle],["Progress Tracker","Progress Tracker",Target],["Transport","Transport",Bus]]
};

function load(key,fallback){try{const x=localStorage.getItem(key);return x?JSON.parse(x):fallback}catch{return fallback}}
function save(key,value){localStorage.setItem(key,JSON.stringify(value))}

function Login({onLogin}){
 const [role,setRole]=useState("admin"),[email,setEmail]=useState(accounts.admin.email),[password,setPassword]=useState(accounts.admin.password),[err,setErr]=useState("");
 const [teacherName,setTeacherName]=useState(teacherAccounts[0]?.name||"");
 const [parentName,setParentName]=useState(parentAccounts[1]?.name||parentAccounts[0]?.name||"");
 const choose=r=>{setRole(r);setErr("");if(r==="teacher"){const t=teacherAccounts.find(x=>x.name===teacherName)||teacherAccounts[0];if(t){setEmail(t.email);setPassword(t.password);setTeacherName(t.name)}}else if(r==="parent"){const p=parentAccounts.find(x=>x.name===parentName)||parentAccounts[0];if(p){setEmail(p.email);setPassword(p.password);setParentName(p.name)}}else{setEmail(accounts.admin.email);setPassword(accounts.admin.password)}};
 const chooseTeacher=name=>{setTeacherName(name);const t=teacherAccounts.find(x=>x.name===name);if(t){setEmail(t.email);setPassword(t.password)}setErr("")};
 const chooseParent=name=>{setParentName(name);const p=parentAccounts.find(x=>x.name===name);if(p){setEmail(p.email);setPassword(p.password)}setErr("")};
 const submit=e=>{e.preventDefault();const normalized=email.trim().toLowerCase();const candidates=role==="teacher"?teacherAccounts:role==="parent"?parentAccounts:[accounts.admin];const a=candidates.find(x=>normalized===x.email.toLowerCase()&&password===x.password);if(a)onLogin(a);else setErr(role==="teacher"?"Invalid teacher login. Select a teacher or enter a valid staff email.":role==="parent"?"Invalid parent login. Select a parent or enter a valid parent email.":"Invalid demo login details")};
 const demoText=role==="teacher"?"Any teacher account · Password: teacher123 · Example: meena.joseph@school.demo":role==="parent"?"Any parent account · Password: parent123 · Example: parent@school.demo":`${accounts.admin.email} / ${accounts.admin.password}`;
 return <div className="login"><div className="login-card"><div className="brand big"><div className="brand-icon"><School/></div><div><b>Bright Future</b><span>Primary School ERP</span></div></div><h1>Welcome back 👋</h1><p className="muted">Choose your school portal to continue.</p><div className="role-grid">{Object.keys(portalAccounts).map(r=><button type="button" className={"role "+(role===r?"selected":"")} onClick={()=>choose(r)} key={r}><span>{r==="admin"?"👨‍💼":r==="teacher"?"👩‍🏫":"👨‍👩‍👧"}</span><b>{portalAccounts[r].role}</b><small>{r==="admin"?"Administration":r==="teacher"?"Teaching & Classwork":"Child & Family"}</small></button>)}</div>{role==="teacher"&&<label className="teacher-login-select">Select Teacher<select value={teacherName} onChange={e=>chooseTeacher(e.target.value)}>{teacherAccounts.map(t=><option key={t.name} value={t.name}>{t.name}</option>)}</select></label>}{role==="parent"&&<label className="teacher-login-select">Select Parent / Child<select value={parentName} onChange={e=>chooseParent(e.target.value)}>{parentAccounts.map(p=><option key={p.name} value={p.name}>{p.name} — {p.child} ({p.className})</option>)}</select></label>}<form onSubmit={submit}><label>Official Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{err&&<div className="error">{err}</div>}<button className="primary full">Login as {portalAccounts[role].role}<ChevronRight size={18}/></button></form><div className="demo-hint"><b>Demo credentials</b><br/>{demoText}<br/><small>Only 3 portals: Admin, Teacher and Parent. All staff teachers use Teacher; each student's parent uses Parent.</small></div></div></div>
}

function Modal({title,onClose,children}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><div className="card-head"><h3>{title}</h3><button type="button" className="iconbtn" onClick={onClose}>✕</button></div>{children}</div></div>}
function Stat({title,value,sub,icon:Icon,onClick}){return <div className={"stat "+(onClick?"clickable":"")} onClick={onClick}><div className="stat-top"><span>{title}</span><div className="stat-icon"><Icon size={19}/></div></div><strong>{value}</strong><small>{sub}</small></div>}
function Card({title,children,action}){return <div className="card"><div className="card-head"><h3>{title}</h3>{action&&<button type="button" className="link" onClick={action[1]}>{action[0]}</button>}</div>{children}</div>}
function Activity({text,time}){return <div className="activity"><span className="dot"></span><div><b>{text}</b><small>{time}</small></div></div>}
function Task({text,done,onClick}){return <div className={"task "+(onClick?"clickable":"")} onClick={onClick}><span className={done?"check done":"check"}>{done?"✓":""}</span><span>{text}</span></div>}
function TimeRows({rows}){return <div>{rows.map((x,i)=><div className="time-row" key={i}><b>{x[1]}</b><span>{x[2]}</span><small>{x[3]}</small></div>)}</div>}

function App(){
 const [user,setUser]=useState(null),[page,setPage]=useState("Dashboard"),[mobile,setMobile]=useState(false),[toast,setToast]=useState("");
 const [students,setStudents]=useState(()=>load("bf_students",initialStudents));
 const [teachers,setTeachers]=useState(()=>load("bf_teachers_v2",initialTeachers));
 const [classes,setClasses]=useState(()=>load("bf_classes",initialClasses));
 const [homeworkItems,setHomeworkItems]=useState(()=>load("bf_homework_v2",initialHomework));
 const [notices,setNotices]=useState(()=>load("bf_notices",initialNotices));
 const [attendance,setAttendance]=useState(()=>load("bf_attendance",{}));
 const [chatMessages,setChatMessages]=useState(()=>load("bf_chat_v3",initialChatMessages));
 const [library,setLibrary]=useState(()=>load("bf_library_v2",initialLibrary));
 const [substitutions,setSubstitutions]=useState(()=>load("bf_substitutions_v1",initialSubstitutions));
 const [availabilityRequests,setAvailabilityRequests]=useState(()=>load("bf_staff_requests_v1",initialAvailabilityRequests));
 const [modal,setModal]=useState(null);
 useEffect(()=>save("bf_students",students),[students]);useEffect(()=>save("bf_teachers_v2",teachers),[teachers]);useEffect(()=>save("bf_classes",classes),[classes]);useEffect(()=>save("bf_homework_v2",homeworkItems),[homeworkItems]);useEffect(()=>save("bf_notices",notices),[notices]);useEffect(()=>save("bf_attendance",attendance),[attendance]);useEffect(()=>save("bf_chat_v3",chatMessages),[chatMessages]);useEffect(()=>save("bf_library_v2",library),[library]);useEffect(()=>save("bf_substitutions_v1",substitutions),[substitutions]);useEffect(()=>save("bf_staff_requests_v1",availabilityRequests),[availabilityRequests]);
 const notify=m=>{setToast(m);window.clearTimeout(window.__bfToast);window.__bfToast=window.setTimeout(()=>setToast(""),2200)};
 if(!user)return <Login onLogin={u=>{setUser(u);setPage("Dashboard")}}/>;
 const nav=navs[user.role];
 const shared={students,setStudents,teachers,setTeachers,classes,setClasses,homeworkItems,setHomeworkItems,notices,setNotices,attendance,setAttendance,chatMessages,setChatMessages,library,setLibrary,substitutions,setSubstitutions,availabilityRequests,setAvailabilityRequests,setModal,notify,setPage};
 const logout=()=>{setUser(null);setPage("Dashboard");setModal(null)};
 return <div className="app"><aside className={mobile?"open":""}><div className="brand"><div className="brand-icon"><School/></div><div><b>Bright Future</b><span>Primary School ERP</span></div></div><div className="portal">{user.role} PORTAL</div><nav>{nav.map(([label,key,Icon])=>{const chatUnread=user.role==="Teacher"&&key==="Parent Messages"?Math.max(0,shared.chatMessages.filter(m=>m.from==="parent").length-load("bf_chat_seen_teacher",0)):user.role==="Parent"&&key==="Teacher Chat"?Math.max(0,shared.chatMessages.filter(m=>m.from==="teacher").length-load("bf_chat_seen_parent",0)):0;return <button type="button" className={page===key?"active":""} onClick={()=>{setPage(key);setMobile(false);if(key==="Parent Messages")save("bf_chat_seen_teacher",shared.chatMessages.filter(m=>m.from==="parent").length);if(key==="Teacher Chat")save("bf_chat_seen_parent",shared.chatMessages.filter(m=>m.from==="teacher").length)}} key={key}><Icon size={18}/><span className="nav-label">{label}</span>{chatUnread>0&&<span className="nav-badge">{chatUnread}</span>}</button>})}</nav><button type="button" className="logout" onClick={logout}><LogOut size={18}/> Logout</button></aside><main><header><button type="button" className="mobile-menu" onClick={()=>setMobile(!mobile)}><Menu/></button><div><h2>{page}</h2><span className="muted">Good morning, {user.name}</span></div><div className="header-right"><button type="button" className="iconbtn" onClick={()=>setPage(user.role==="Parent"?"Notices":"Notices")}>🔔</button><button type="button" className="avatar" onClick={()=>setPage(user.role==="Teacher"?"My Profile":"Dashboard")}>{user.name[0]}</button></div></header><section className="content">{renderPage(page,user,shared)}</section></main>{toast&&<div className="toast">{toast}</div>}{modal}</div>
}

function renderPage(page,u,s){const r=u.role;if(page==="Dashboard")return <Dashboard u={u} s={s}/>;if(page.includes("Timetable"))return <Timetable role={r} u={u} s={s}/>;if(page==="Students"||page==="My Students")return <Students role={r} s={s}/>;if(page==="Teachers")return <Teachers s={s}/>;if(page==="Staff Requests")return <StaffRequests s={s}/>;if(page==="Staff Substitution")return <SubstitutionPlanner s={s}/>;if(page==="Report Unavailability")return <ReportUnavailability u={u} s={s}/>;if(page==="Substitution Duty")return <SubstitutionDuty u={u} s={s}/>;if(page==="Classes")return <Classes s={s}/>;if(page==="Attendance"||page==="My Attendance")return <Attendance role={r} u={u} s={s}/>;if(page==="Homework"||page==="My Homework")return <Homework role={r} s={s}/>;if(page==="Library")return <LibraryPage role={r} s={s}/>;if(["Exams & Marks","Enter Marks","Marks / Report Card","My Marks"].includes(page))return <Marks role={r} u={u} s={s}/>;if(page==="Fees"||page==="Fees & Payment")return <Fees role={r} s={s}/>;if(page==="Notices")return <Notices role={r} s={s}/>;if(page==="Calendar"||page==="Events")return <Calendar role={r} s={s}/>;if(page==="Transport")return <Transport role={r} u={u} s={s}/>;if(page==="Teacher Chat"||page==="Parent Messages")return <Chat role={r} u={u} s={s}/>;if(page==="User Management")return <UsersPage s={s}/>;if(page==="Reports")return <Reports s={s}/>;if(page==="Settings")return <SettingsPage s={s}/>;if(page==="Leave Request")return <Leave s={s}/>;if(page==="My Profile")return <Profile u={u} s={s}/>;if(page==="My Child")return <Child u={u} s={s}/>;if(page==="Progress Tracker")return <ProgressTracker role={r} u={u} s={s}/>;return <Dashboard u={u} s={s}/>}

function Dashboard({u,s}){const r=u.role;const go=p=>{s.setPage(p);s.notify("Opening "+p);};if(r==="Admin")return <><div className="welcome"><div><h1>School Overview</h1><p>Manage your primary school from one place.</p></div><button type="button" className="primary" onClick={()=>s.setModal(<QuickAction s={s} onClose={()=>s.setModal(null)}/>)}>+ Quick Action</button></div><div className="stats"><Stat title="Total Students" value={s.students.length} sub="Active records" icon={Users} onClick={()=>go("Students")}/><Stat title="Teachers" value={s.teachers.length} sub="Active staff" icon={GraduationCap} onClick={()=>go("Teachers")}/><Stat title="Attendance Today" value="94.6%" sub="School average" icon={ClipboardCheck} onClick={()=>go("Attendance")}/><Stat title="Fees Collected" value="₹8.4L" sub="82% of monthly target" icon={Wallet} onClick={()=>go("Fees")}/></div><div className="grid2"><Card title="Today's Highlights"><Activity text="Class 3-A Mathematics" time="Priya Sharma · 09:00 AM"/><Activity text="Inter-house Quiz" time="School Auditorium · 02:00 PM"/><Activity text="Parent Meeting" time="Saturday · 10:00 AM"/></Card><Card title="Recent Activity"><Activity text={s.homeworkItems.length+" homework assignments available"} time="Live data"/><Activity text={s.students.length+" student records"} time="Live data"/><Activity text={s.notices.length+" notices published"} time="Live data"/></Card></div></>;
 if(r==="Teacher")return <><div className="welcome"><div><h1>Teacher Dashboard</h1><p>Your classes and daily teaching tasks.</p></div><button type="button" className="pill" onClick={()=>go("My Timetable")}>{u.name} · {s.teachers.find(t=>t.name===u.name)?.subject||"Teacher"}</button></div><div className="stats"><Stat title="My Students" value={s.students.length} sub="Grade 3-A" icon={Users} onClick={()=>go("My Students")}/><Stat title="Today's Classes" value="4" sub="Next at 10:00 AM" icon={Clock} onClick={()=>go("My Timetable")}/><Stat title="Attendance" value="96%" sub="This month" icon={ClipboardCheck} onClick={()=>go("Attendance")}/><Stat title="Pending Tasks" value={s.homeworkItems.filter(x=>!x.completed).length} sub="Homework" icon={BookOpen} onClick={()=>go("Homework")}/></div><div className="grid2"><Card title="Today's Timetable"><TimeRows rows={defaultTT.filter(x=>x[0]==="Monday").slice(0,3)}/></Card><Card title="My Tasks"><Task text="Mark Grade 3-A attendance" onClick={()=>go("Attendance")}/><Task text="Review Maths homework" onClick={()=>go("Homework")}/><Task text="Enter Unit Test marks" onClick={()=>go("Enter Marks")}/><Task text="Submit leave request" onClick={()=>go("Leave Request")}/></Card></div></>;
 if(r==="Parent")return <><div className="welcome"><div><h1>Hello, {u.name} 👋</h1><p>Here is your child's school progress.</p></div><button type="button" className="pill" onClick={()=>go("My Child")}>Child · Ananya Priya</button></div><div className="stats"><Stat title="Attendance" value="98%" sub="Excellent attendance" icon={ClipboardCheck} onClick={()=>go("Attendance")}/><Stat title="Average Marks" value="91%" sub="Unit Test 1" icon={FileText} onClick={()=>go("Marks / Report Card")}/><Stat title="Homework" value={s.homeworkItems.length} sub="Shared assignments" icon={BookOpen} onClick={()=>go("Homework")}/><Stat title="Fees" value="Paid" sub="Next due: Oct 10" icon={Wallet} onClick={()=>go("Fees & Payment")}/></div><div className="grid2"><Card title="Today's Timetable"><TimeRows rows={defaultTT.filter(x=>x[0]==="Monday").slice(0,3)}/></Card><Card title="Recent Updates"><Activity text="Mathematics homework assigned" time="Today, 9:15 AM"/><Activity text="Ananya marked Present" time="Today, 8:45 AM"/><Activity text="Unit Test marks published" time="Yesterday"/></Card></div></>;
 return null;
}

function QuickAction({s,onClose}){const [type,setType]=useState("homework");return <Modal title="Quick Action" onClose={onClose}><div className="formgrid"><label>Action<select value={type} onChange={e=>setType(e.target.value)}><option value="homework">Add Homework</option><option value="student">Add Student</option><option value="teacher">Add Teacher</option><option value="notice">New Notice</option></select></label><button className="primary" type="button" onClick={()=>{onClose();s.setModal(type==="homework"?<HomeworkForm s={s} onClose={()=>s.setModal(null)}/>:type==="student"?<StudentForm s={s} onClose={()=>s.setModal(null)}/>:type==="teacher"?<TeacherForm s={s} onClose={()=>s.setModal(null)}/>:<NoticeForm s={s} onClose={()=>s.setModal(null)}/>);}}>Continue</button></div></Modal>}

function Students({role,s}){const [q,setQ]=useState("");const data=s.students.filter(x=>(x.name+x.className+x.roll+x.parent).toLowerCase().includes(q.toLowerCase()));return <><PageTools title={role==="Teacher"?"My Students":"Student Management"} sub="Manage student records and class details." action={(role==="Teacher"||role==="Admin")?()=>s.setModal(<StudentForm s={s} onClose={()=>s.setModal(null)}/>):null} actionText="＋ Add Student"/><div className="card"><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search student name, class or roll no."/></div><table><thead><tr><th>Student</th><th>Class</th><th>Roll No.</th><th>Parent</th><th>Attendance</th><th>Actions</th></tr></thead><tbody>{data.map((x,i)=><tr key={x.name+x.roll}><td><b>{x.name}</b></td><td>{x.className}</td><td>{x.roll}</td><td>{x.parent}</td><td><span className="good">{x.attendance}</span></td><td><button type="button" className="iconbtn" onClick={()=>s.setModal(<StudentForm s={s} existing={x} index={s.students.indexOf(x)} onClose={()=>s.setModal(null)}/>)}><Edit3 size={16}/></button><button type="button" className="iconbtn" onClick={()=>{if(confirm("Delete this student?")){s.setStudents(s.students.filter((_,j)=>j!==s.students.indexOf(x)));s.notify("Student deleted")}}}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div></>}
function StudentForm({s,onClose,existing,index}){const [form,setForm]=useState(existing||{name:"",className:"Grade 3-A",roll:"",parent:"",attendance:"100%"});const set=(k,v)=>setForm({...form,[k]:v});const submit=e=>{e.preventDefault();if(!form.name.trim()||!form.roll.trim()||!form.parent.trim())return s.notify("Fill all required student details");if(index!==undefined)s.setStudents(s.students.map((x,i)=>i===index?form:x));else s.setStudents([...s.students,form]);s.notify(index!==undefined?"Student updated successfully":"Student added successfully");onClose()};return <Modal title={index!==undefined?"Edit Student":"Add Student"} onClose={onClose}><form className="formgrid" onSubmit={submit}><label>Name<input required value={form.name} onChange={e=>set("name",e.target.value)}/></label><label>Class<input value={form.className} onChange={e=>set("className",e.target.value)}/></label><label>Roll No.<input required value={form.roll} onChange={e=>set("roll",e.target.value)}/></label><label>Parent Name<input required value={form.parent} onChange={e=>set("parent",e.target.value)}/></label><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">{index!==undefined?"Update Student":"Add Student"}</button></div></form></Modal>}

function Teachers({s}){return <><PageTools title="Teacher Management" sub="Teachers, subjects and assigned classes." action={()=>s.setModal(<TeacherForm s={s} onClose={()=>s.setModal(null)}/>)} actionText="＋ Add Teacher"/><div className="teacher-grid">{s.teachers.map((t,i)=><div className="teacher-card" key={t.name}><div className="avatar large">{t.name[0]}</div><div><h3>{t.name}</h3><p>{t.subject}</p><small>{t.classes}</small></div><button type="button" className="link" onClick={()=>s.setModal(<TeacherForm s={s} existing={t} index={i} onClose={()=>s.setModal(null)}/>)}>Edit</button></div>)}</div></>}
function TeacherForm({s,onClose,existing,index}){const [form,setForm]=useState(existing||{name:"",subject:"",classes:"Grade 3-A"});const set=(k,v)=>setForm({...form,[k]:v});const submit=e=>{e.preventDefault();if(!form.name||!form.subject)return s.notify("Fill teacher details");if(index!==undefined)s.setTeachers(s.teachers.map((x,i)=>i===index?form:x));else s.setTeachers([...s.teachers,form]);s.notify(index!==undefined?"Teacher updated successfully":"Teacher added successfully");onClose()};return <Modal title={index!==undefined?"Edit Teacher":"Add Teacher"} onClose={onClose}><form className="formgrid" onSubmit={submit}><label>Name<input required value={form.name} onChange={e=>set("name",e.target.value)}/></label><label>Subject<input required value={form.subject} onChange={e=>set("subject",e.target.value)}/></label><label>Assigned Classes<input value={form.classes} onChange={e=>set("classes",e.target.value)}/></label><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">{index!==undefined?"Update Teacher":"Add Teacher"}</button></div></form></Modal>}

function Classes({s}){const [open,setOpen]=useState(false),[name,setName]=useState("");return <><PageTools title="Classes & Subjects" sub="Primary sections, class teachers and subjects." action={()=>setOpen(true)} actionText="＋ Add Class"/><div className="class-grid">{s.classes.map((c,i)=><div className="class-card" key={c} onClick={()=>s.notify("Opened "+c+" details")} role="button" tabIndex="0"><span>Class</span><h2>{c}</h2><p>{20+i*3} Students</p><small>Class Teacher · {s.teachers[i%s.teachers.length]?.name||"Not assigned"}</small><div className="subject-line">{primarySubjects.join(" · ")}</div></div>)}</div>{open&&<Modal title="Add Class" onClose={()=>setOpen(false)}><form className="formgrid" onSubmit={e=>{e.preventDefault();if(!name.trim())return s.notify("Enter class name");s.setClasses([...s.classes,name.trim()]);s.notify("Class added successfully");setName("");setOpen(false)}}><label>Class Name<input autoFocus required value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Grade 6-A"/></label><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary">Add Class</button></div></form></Modal>}</>}

function Timetable({role,u,s}){const [rows,setRows]=useState(()=>load("bf_timetable_v2",defaultTT));const [open,setOpen]=useState(false);const saveRows=r=>{setRows(r);save("bf_timetable_v2",r)};let shown=role==="Teacher"?rows.filter(x=>x[3]===u?.name):rows;return <><PageTools title={role==="Admin"?"Timetable & Teacher Assignment":"My Timetable"} sub="Assignments are shared across portals." action={role==="Admin"?()=>setOpen(true):null} actionText="＋ Assign Period"/><div className="card"><div className="tt-banner">🔗 <b>Connected timetable:</b> changes are saved in this browser and visible to the relevant portals.</div><table><thead><tr><th>Day</th><th>Time</th><th>Subject</th><th>Teacher</th><th>Class</th><th>Action</th></tr></thead><tbody>{shown.map((x,i)=><tr key={i}><td><b>{x[0]}</b></td><td>{x[1]}</td><td>{x[2]}</td><td>{x[3]}</td><td>Grade 3-A</td><td><button type="button" className="iconbtn" onClick={()=>s.notify("Period is active: "+x[2])}><CheckCircle2 size={16}/></button></td></tr>)}</tbody></table></div>{open&&<PeriodForm teachers={s.teachers} onClose={()=>setOpen(false)} onSave={r=>{saveRows([...rows,r]);s.notify("Period assigned successfully");setOpen(false)}}/>}</>}
function PeriodForm({teachers,onClose,onSave}){const [day,setDay]=useState("Monday"),[time,setTime]=useState("12:15 PM"),[subject,setSubject]=useState("Mathematics"),[teacher,setTeacher]=useState(teachers[0]?.name||"");return <Modal title="Assign Period" onClose={onClose}><form className="formgrid" onSubmit={e=>{e.preventDefault();onSave([day,time,subject,teacher])}}><label>Day<select value={day} onChange={e=>setDay(e.target.value)}>{["Monday","Tuesday","Wednesday","Thursday","Friday"].map(x=><option key={x}>{x}</option>)}</select></label><label>Time<input value={time} onChange={e=>setTime(e.target.value)}/></label><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>Teacher<select value={teacher} onChange={e=>setTeacher(e.target.value)}>{teachers.map(t=><option key={t.name}>{t.name}</option>)}</select></label><button className="primary">Save Period</button></form></Modal>}

function Attendance({role,u,s}){const data=role==="Parent"?s.students.filter(x=>x.name===u?.child):role==="Student"?s.students.filter(x=>x.name==="Aarav Kumar"):s.students;const mark=(name,status)=>s.setAttendance({...s.attendance,[name]:status});return <><PageTools title="Attendance" sub="Click a status to change it, then save the records." action={role!=="Parent"&&role!=="Student"?()=>{s.notify("Attendance records saved")} :null} actionText="Save Attendance"/><div className="stats"><Stat title="Present Today" value={Object.values(s.attendance).filter(x=>x==="Present").length||data.length} sub="Current records" icon={CheckCircle2}/><Stat title="Absent" value={Object.values(s.attendance).filter(x=>x==="Absent").length} sub="Current records" icon={Users}/><Stat title="Late" value={Object.values(s.attendance).filter(x=>x==="Late").length} sub="Current records" icon={Clock}/></div><div className="card"><table><thead><tr><th>Student</th><th>Class</th><th>Attendance</th><th>Today</th></tr></thead><tbody>{data.map(x=>{const st=s.attendance[x.name]||"Present";return <tr key={x.name}><td><b>{x.name}</b></td><td>{x.className}</td><td>{x.attendance}</td><td><button type="button" className={st==="Present"?"status present":"status"} onClick={()=>mark(x.name,st==="Present"?"Absent":"Present")}>{st}</button><button type="button" className="link" onClick={()=>mark(x.name,"Late")}>Late</button></td></tr>})}</tbody></table></div></>}

function Homework({role,s}){const canAdd=role==="Teacher"||role==="Admin";const items=s.homeworkItems;const add=form=>{s.setHomeworkItems([...items,{...form,completed:false}]);s.notify("Homework added successfully — visible to students and parents")};const complete=i=>{s.setHomeworkItems(items.map((x,j)=>j===i?{...x,completed:true}:x));s.notify("Homework marked completed")};return <><PageTools title={canAdd?"Homework Management":"Homework"} sub={canAdd?"Create assignments that immediately appear in Student and Parent portals.":"Assignments shared by the school."} action={canAdd?()=>s.setModal(<HomeworkForm s={s} onClose={()=>s.setModal(null)} onAdd={add}/>):null} actionText="＋ Add Homework"/><div className="homework-grid">{items.map((h,i)=><div className="hw" key={i}><span className="hw-icon">📚</span><div><b>{h.subject}</b><h3>{h.title}</h3><small>Grade 3-A · Due {h.due}</small></div>{role==="Student"?<button type="button" className={h.completed?"status present":"status"} disabled={h.completed} onClick={()=>complete(i)}>{h.completed?"Completed":"Mark Done"}</button>:<button type="button" className={h.completed?"status present":"status"} onClick={()=>s.notify(h.completed?"This homework is completed":"Assigned to Grade 3-A — visible to parents and students")}>{h.completed?"Completed":"Assigned"}</button>}</div>)}</div></>}
function HomeworkForm({s,onClose,onAdd}){const [subject,setSubject]=useState("Mathematics"),[title,setTitle]=useState(""),[due,setDue]=useState("Tomorrow");const submit=e=>{e.preventDefault();if(!title.trim())return s.notify("Please enter homework title");(onAdd||((f)=>s.setHomeworkItems([...s.homeworkItems,{...f,completed:false}])) )({subject,title:title.trim(),due});s.notify("Homework added successfully");onClose()};return <Modal title="Add Homework" onClose={onClose}><form className="formgrid" onSubmit={submit}><label>Subject<select value={subject} onChange={e=>setSubject(e.target.value)}><option>Mathematics</option><option>English</option><option>EVS</option><option>Tamil</option><option>Science</option><option>Hindi</option><option>Computer Science</option><option>General Knowledge</option><option>Art & Craft</option><option>Music</option><option>Yoga</option><option>Physical Education</option><option>Moral Science</option></select></label><label>Homework Title<input required autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Complete exercise 5"/></label><label>Due<select value={due} onChange={e=>setDue(e.target.value)}><option>Today</option><option>Tomorrow</option><option>Friday</option><option>Next Monday</option></select></label><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">Add Homework</button></div></form></Modal>}

function Marks({role,u,s}){const [local,setLocal]=useState(marks);const editable=role==="Teacher"||role==="Admin";return <><PageTools title={editable?"Exams & Marks":"My Marks / Report Card"} sub={editable?"Enter and save assessment marks.":"Academic performance overview."} action={editable?()=>{s.notify("Marks saved successfully")}:()=>s.notify("Report card opened")} actionText={editable?"Save Marks":"View Report"}/><div className="card"><div className="report-head"><div><b>{role==="Parent"?(u?.child||"Ananya Priya"):"Aarav Kumar"}</b><small>Grade 3-A · Unit Test 1</small></div><div className="score">{Math.round(local.reduce((a,x)=>a+Number(x.score),0)/local.length)}%<small>Overall</small></div></div><table><thead><tr><th>Subject</th><th>Score</th><th>Performance</th></tr></thead><tbody>{local.map((m,i)=><tr key={m.subject}><td><b>{m.subject}</b></td><td>{editable?<input className="table-input" type="number" min="0" max="100" value={m.score} onChange={e=>setLocal(local.map((x,j)=>j===i?{...x,score:e.target.value}:x))}/>:m.score+" / 100"}</td><td><span className="good">{Number(m.score)>=90?"Excellent":Number(m.score)>=75?"Good":"Needs Practice"}</span></td></tr>)}</tbody></table></div></>}

function Fees({role,s}){const [paid,setPaid]=useState(false);return <><PageTools title={role==="Admin"?"Fees Management":"Fees & Payment"} sub="Track fees and payment status." action={role!=="Admin"?()=>{setPaid(true);s.notify("Payment successful in demo mode")}:()=>s.notify("Fee report refreshed")} actionText={role!=="Admin"?"Pay Fees":"Refresh"}/><div className="stats"><Stat title="Annual Fee" value="₹48,000" sub="Academic year 2026–27" icon={Wallet}/><Stat title="Paid" value={paid?"₹48,000":"₹32,000"} sub={paid?"Paid now":"Up to September"} icon={CheckCircle2}/><Stat title="Balance" value={paid?"₹0":"₹16,000"} sub={paid?"Cleared":"Next due Oct 10"} icon={Wallet}/></div><div className="card"><table><thead><tr><th>Fee Head</th><th>Amount</th><th>Status</th><th>Due Date</th><th>Action</th></tr></thead><tbody>{[["Tuition Fee","₹12,000","Paid","Sep 10"],["Transport Fee","₹4,000","Paid","Sep 10"],["Activity Fee","₹2,000",paid?"Paid":"Pending","Oct 10"]].map(x=><tr key={x[0]}><td><b>{x[0]}</b></td><td>{x[1]}</td><td><span className={x[2]==="Paid"?"present":"pending"}>{x[2]}</span></td><td>{x[3]}</td><td><button type="button" className="link" onClick={()=>s.notify(x[2]==="Paid"?"Receipt opened":"Payment selected")}>{x[2]==="Paid"?"Receipt":"Pay"}</button></td></tr>)}</tbody></table></div></>}


const initialProgress={
 "Aarav Kumar":{academic:90,homework:90,attendance:96,participation:88,reading:92,math:86,goal:"Complete 20 multiplication problems",goalDone:false,remark:"Doing very well. Keep practising Mathematics."},
 "Ananya Priya":{academic:91,homework:88,attendance:98,participation:94,reading:96,math:89,goal:"Read one story book this month",goalDone:false,remark:"Excellent participation and reading skills."}
};
function ProgressTracker({role,u,s}){
 const editable=role==="Teacher"||role==="Admin";
 const defaultStudent=role==="Parent"?(u?.child||"Ananya Priya"):role==="Student"?"Aarav Kumar":(s.students[0]?.name||"Aarav Kumar");
 const [all,setAll]=useState(()=>load("bf_progress",initialProgress));
 const [selected,setSelected]=useState(defaultStudent);
 const [draft,setDraft]=useState(()=>load("bf_progress",initialProgress)[defaultStudent]||initialProgress["Aarav Kumar"]);
 useEffect(()=>save("bf_progress",all),[all]);
 const choose=name=>{setSelected(name);setDraft(all[name]||{academic:80,homework:80,attendance:90,participation:80,reading:80,math:80,goal:"Set a monthly learning goal",goalDone:false,remark:""})};
 const set=(k,v)=>setDraft({...draft,[k]:v});
 const saveProgress=()=>{setAll({...all,[selected]:draft});s.notify("Progress updated — visible to Student and Parent portals")};
 const markGoal=()=>{const next={...draft,goalDone:!draft.goalDone};setDraft(next);setAll({...all,[selected]:next});s.notify(next.goalDone?"Goal completed 🎉":"Goal marked incomplete")};
 const avg=Math.round((Number(draft.academic)+Number(draft.homework)+Number(draft.attendance)+Number(draft.participation))/4);
 return <><PageTools title="Student Progress Tracker" sub={editable?"Update a student's overall learning progress and monthly goal.":"Track learning growth, activities and monthly goals."} action={editable?saveProgress:null} actionText="Save Progress"/>
 <div className="grid2"><Card title="Student"><label>Student<select value={selected} disabled={role==="Parent"||role==="Student"} onChange={e=>choose(e.target.value)}>{s.students.map(x=><option key={x.name}>{x.name}</option>)}</select></label><div className="progress-hero"><div className="avatar huge">{selected[0]}</div><div><h2>{selected}</h2><p>{s.students.find(x=>x.name===selected)?.className||"Grade 3-A"}</p><strong>{avg}% Overall Progress</strong></div></div></Card>
 <Card title="Monthly Goal"><div className="goal-box"><div><span className="goal-icon">🎯</span><div><b>{draft.goal||"No goal set"}</b><small>{draft.goalDone?"Completed this month":"In progress"}</small></div></div>{editable?<button type="button" className={draft.goalDone?"status present":"primary"} onClick={markGoal}>{draft.goalDone?"Completed":"Mark Complete"}</button>:<button type="button" className={draft.goalDone?"status present":"secondary"} onClick={role==="Student"?markGoal:undefined}>{draft.goalDone?"Completed":"In Progress"}</button>}</div></Card></div>
 <div className="progress-grid">{[["Academic Performance","academic","📚"],["Homework Completion","homework","📝"],["Attendance","attendance","📅"],["Class Participation","participation","🙋"],["Reading Skills","reading","📖"],["Mathematics","math","➗"]].map(([label,key,icon])=><div className="progress-card" key={key}><div><span>{icon}</span><b>{label}</b><strong>{draft[key]}%</strong></div><div className="bar"><i style={{width:Number(draft[key])+"%"}}></i></div>{editable&&<input type="range" min="0" max="100" value={draft[key]} onChange={e=>set(key,e.target.value)}/>}</div>)}</div>
 <Card title="Teacher Remark"><textarea rows="3" disabled={!editable} value={draft.remark||""} onChange={e=>set("remark",e.target.value)} placeholder="Add a remark about the student's progress..."/></Card>
 </>;
}

function LibraryPage({role,s}){
 const canManage=role==="Admin"||role==="Teacher";
 const studentName=role==="Parent"?"Ananya Priya":"";
 const [q,setQ]=useState(""); const [cat,setCat]=useState("All");
 const [open,setOpen]=useState(false); const [borrowed,setBorrowed]=useState(false);
 const books=s.library||[];
 const filtered=books.filter(b=>(cat==="All"||b.category===cat)&&(b.title+b.author+b.category).toLowerCase().includes(q.toLowerCase()));
 const issue=id=>{const book=books.find(b=>b.id===id);if(!book||book.available<1)return s.notify("No copy available");const target=studentName||prompt("Enter student name to issue this book:","Aarav Kumar");if(!target||!target.trim())return s.notify("Student name is required");const next=books.map(b=>b.id===id?{...b,available:b.available-1,issuedTo:target.trim(),due:"Sep 20"}:b);s.setLibrary(next);setBorrowed(true);s.notify(book.title+" issued to "+target.trim())};
 const returnBook=id=>{const next=books.map(b=>b.id===id?{...b,available:Math.min(b.total,b.available+1),issuedTo:"",due:""}:b);s.setLibrary(next);s.notify("Book returned successfully")};
 const addBook=book=>{s.setLibrary([...books,{...book,id:Date.now()}]);setOpen(false);s.notify("Book added to library")};
 const myBooks=studentName?books.filter(b=>b.issuedTo===studentName):[];
 return <><PageTools title="Library Management" sub={canManage?"Manage books, issue and return records.":"Browse books and view your borrowed books."} action={canManage?()=>setOpen(true):null} actionText="＋ Add Book"/>
 <div className="stats"><Stat title="Total Books" value={books.reduce((a,b)=>a+b.total,0)} sub="All copies" icon={Library}/><Stat title="Available" value={books.reduce((a,b)=>a+b.available,0)} sub="Ready to issue" icon={CheckCircle2}/><Stat title={canManage?"Issued Books":"My Books"} value={canManage?books.filter(b=>b.issuedTo).length:myBooks.length} sub={canManage?"Currently borrowed":"Currently borrowed"} icon={BookOpen}/></div>
 <div className="card"><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search story, subject, activity or author..."/><select value={cat} onChange={e=>setCat(e.target.value)}><option>All</option>{[...new Set(books.map(b=>b.category))].map(c=><option key={c}>{c}</option>)}</select></div>
 <table><thead><tr><th>Book</th><th>Author</th><th>Category</th><th>Age Group</th><th>Copies</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map(b=><tr key={b.id}><td><b>{b.title}</b></td><td>{b.author}</td><td>{b.category}</td><td>{b.ageGroup||"Primary"}</td><td>{b.available} / {b.total}</td><td><span className={b.available>0?"present":"pending"}>{b.available>0?"Available":"Not Available"}</span></td><td>{canManage?(b.issuedTo?<button type="button" className="link" onClick={()=>returnBook(b.id)}>Return</button>:<button type="button" className="link" onClick={()=>issue(b.id)}>Issue</button>):<button type="button" className="link" disabled={b.available<1||b.issuedTo===studentName} onClick={()=>issue(b.id)}>{b.issuedTo===studentName?"Borrowed":"Borrow"}</button>}</td></tr>)}</tbody></table></div>
 {studentName&&<div className="card" style={{marginTop:18}}><div className="card-head"><h3>My Borrowed Books</h3><span className="pill">{studentName}</span></div>{myBooks.length?myBooks.map(b=><div className="activity" key={b.id}><span className="dot"></span><div><b>{b.title}</b><small>Due {b.due}</small></div><span className="pending">Issued</span></div>):<p className="muted">No books borrowed yet.</p>}</div>}
 {open&&<LibraryForm onClose={()=>setOpen(false)} onSave={addBook}/>}</>;
}
function LibraryForm({onClose,onSave}){const [title,setTitle]=useState(""),[author,setAuthor]=useState(""),[category,setCategory]=useState("Story"),[ageGroup,setAgeGroup]=useState("6–10 Years"),[total,setTotal]=useState(1);return <Modal title="Add Primary School Book" onClose={onClose}><form className="formgrid" onSubmit={e=>{e.preventDefault();if(!title.trim()||!author.trim())return;onSave({title:title.trim(),author:author.trim(),category,ageGroup,total:Number(total),available:Number(total),issuedTo:"",due:""})}}><label>Book Title<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Charlotte's Web"/></label><label>Author<input required value={author} onChange={e=>setAuthor(e.target.value)} placeholder="Author name"/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option>Story</option><option>Mathematics</option><option>EVS</option><option>Tamil</option><option>Life Skills</option><option>Activity</option></select></label><label>Age Group<select value={ageGroup} onChange={e=>setAgeGroup(e.target.value)}><option>5–8 Years</option><option>6–10 Years</option><option>7–11 Years</option><option>8–12 Years</option></select></label><label>Total Copies<input type="number" min="1" value={total} onChange={e=>setTotal(e.target.value)}/></label><button className="primary">Add Book</button></form></Modal>}

function Notices({role,s}){const canManage=role==="Admin"||role==="Teacher";return <><PageTools title="Notices & Announcements" sub={canManage?"Publish and manage school communication.":"View school communication and important updates."} action={canManage?()=>s.setModal(<NoticeForm s={s} onClose={()=>s.setModal(null)}/>):null} actionText="＋ New Notice"/><div className="notice-grid">{s.notices.map((n,i)=><div className="notice" key={i}><span>{n.icon}</span><div><h3>{n.title}</h3><small>{n.date}</small><p>{n.body}</p>{(role==="Admin"||role==="Teacher")&&<button type="button" className="link" onClick={()=>{if(confirm("Delete this notice?")){s.setNotices(s.notices.filter((_,j)=>j!==i));s.notify("Notice deleted")}}}>Delete</button>}</div></div>)}</div></>}
function NoticeForm({s,onClose}){const [title,setTitle]=useState(""),[body,setBody]=useState(""),[date,setDate]=useState("Today"),[icon,setIcon]=useState("📢");return <Modal title="New Notice" onClose={onClose}><form className="formgrid" onSubmit={e=>{e.preventDefault();if(!title.trim()||!body.trim())return s.notify("Enter notice title and message");s.setNotices([...s.notices,{icon,title:title.trim(),date,body:body.trim()}]);s.notify("Notice published successfully");onClose()}}><label>Title<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Date<input value={date} onChange={e=>setDate(e.target.value)}/></label><label>Message<textarea required rows="4" value={body} onChange={e=>setBody(e.target.value)}/></label><label>Icon<input value={icon} onChange={e=>setIcon(e.target.value)}/></label><button className="primary">Publish Notice</button></form></Modal>}

function Calendar({s,role}){const canManage=role==="Admin"||role==="Teacher";const [events,setEvents]=useState(()=>load("bf_events",[{day:5,title:"Parent Meeting"},{day:15,title:"Inter-house Quiz"},{day:22,title:"Unit Test"}]));const [open,setOpen]=useState(false);const add=e=>{const next=[...events,e];setEvents(next);save("bf_events",next);s.notify("Calendar event added");setOpen(false)};return <><PageTools title="School Calendar" sub="Events, exams and holidays." action={canManage?()=>setOpen(true):null} actionText="＋ Add Event"/><div className="calendar"><div className="month"><button type="button" onClick={()=>s.notify("Previous month")}>‹</button><h2>September 2026</h2><button type="button" onClick={()=>s.notify("Next month")}>›</button></div><div className="week">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=><b key={d}>{d}</b>)}{Array.from({length:30},(_,i)=>{const ev=events.find(e=>e.day===i+1);return <div key={i} className={(i+1===8?"today ":"")+"day"} onClick={()=>ev?s.notify(ev.title+" selected"):setOpen(true)} style={{cursor:"pointer"}}><b>{i+1}</b>{ev&&<small>{ev.title}</small>}</div>})}</div></div>{open&&<EventForm onClose={()=>setOpen(false)} onSave={add}/>}</>}
function EventForm({onClose,onSave}){const [day,setDay]=useState(10),[title,setTitle]=useState("");return <Modal title="Add Calendar Event" onClose={onClose}><form className="formgrid" onSubmit={e=>{e.preventDefault();if(!title.trim())return;onSave({day:Number(day),title:title.trim()})}}><label>Day<input type="number" min="1" max="30" value={day} onChange={e=>setDay(e.target.value)}/></label><label>Event<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Sports Day"/></label><button className="primary">Add Event</button></form></Modal>}

function Transport({s,role,u}){const [booked,setBooked]=useState(false);return <><PageTools title="Transport" sub={role==="Parent"?"View your child's route, stop and pickup status.":"Manage bus routes, stops and assigned students."} action={role==="Parent"?()=>{setBooked(!booked);s.notify(booked?"Pickup tracking stopped":"Pickup tracking started")}:()=>s.notify("Transport management opened")} actionText={role==="Parent"?(booked?"Stop Tracking":"Track Child Bus"):"Manage Routes"}/><div className="grid2"><Card title="Route 4 – North Zone"><div className="route"><b>🚌 TN 38 AB 2026</b><span>Driver: Suresh Kumar</span><span>Pickup: 7:35 AM</span><span>Students: 42</span><span className="present">{booked?"Tracking Live":"On Schedule"}</span></div></Card><Card title="Today's Pickup"><Activity text={`${role==="Parent"?(u?.child||"Child"):"Aarav Kumar"} · 7:40 AM`} time="Main Road Stop"/><Activity text={role==="Parent"?"Your child's pickup · 7:50 AM":"Ananya Priya · 7:50 AM"} time="Temple Stop"/><button type="button" className="primary" onClick={()=>s.notify("Route details opened")}>View Route</button></Card></div></>}

function ReportUnavailability({u,s}){
 const teacher=s.teachers.find(t=>t.name===u.name)||s.teachers[0];
 const [day,setDay]=useState("Today"),[reason,setReason]=useState("Health issue / emergency"),[note,setNote]=useState("");
 const periods=defaultTT.filter(x=>x[0]==="Monday"&&x[3]===teacher.name).map(x=>({time:x[1],subject:x[2]}));
 const [selected,setSelected]=useState(()=>periods.length?[periods[periods.length-1].time]:[]);
 const toggle=p=>setSelected(v=>v.includes(p)?v.filter(x=>x!==p):[...v,p]);
 const submit=e=>{e.preventDefault();if(!selected.length)return s.notify("Select at least one affected period");const items=selected.map(time=>{const row=defaultTT.find(x=>x[0]==="Monday"&&x[1]===time&&x[3]===teacher.name);return {period:time,subject:row?.[2]||teacher.subject,classes:(teacher.classes||"").split(" / ")[0]}});const req={id:Date.now(),teacher:teacher.name,day,reason,note:note.trim(),items,status:"Pending",createdAt:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})};s.setAvailabilityRequests([...s.availabilityRequests,req]);s.notify("Unavailability request sent to Admin");setNote("");setSelected([])};
 const mine=s.availabilityRequests.filter(x=>x.teacher===u.name);
 return <><PageTools title="Report Unavailability" sub="Tell the Admin when you are suddenly unavailable. The Admin will arrange the substitute."/><div className="tt-banner">📩 <b>Teacher → Admin:</b> submit the affected periods here. You do not assign another teacher yourself.</div><div className="grid2"><Card title="New Unavailability Request"><form className="formgrid" onSubmit={submit}><label>Date / Day<select value={day} onChange={e=>setDay(e.target.value)}><option>Today</option><option>Tomorrow</option><option>Wednesday</option><option>Thursday</option><option>Friday</option></select></label><label>Reason<select value={reason} onChange={e=>setReason(e.target.value)}><option>Health issue / emergency</option><option>Staff meeting</option><option>Half-day leave</option><option>Personal work</option></select></label><label>Affected periods<div className="period-picks">{periods.length?periods.map(x=><button type="button" key={x.time} className={selected.includes(x.time)?"status present":"status"} onClick={()=>toggle(x.time)}>{x.time} · {x.subject}</button>):<span className="muted">No timetable periods found for this teacher.</span>}</div></label><label>Note (optional)<textarea rows="3" value={note} onChange={e=>setNote(e.target.value)} placeholder="Example: I am unavailable for the afternoon class."/></label><button className="primary"><Send size={16}/> Send to Admin</button></form></Card><Card title="What happens next"><Activity text="Request reaches Admin" time="Pending approval"/><Activity text="Admin checks affected classes" time="Date + period + subject"/><Activity text="ERP finds available teacher" time="Free period + subject priority"/><Activity text="Substitute gets duty notification" time="Teacher portal"/></Card></div><div className="card"><div className="card-head"><h3>My Requests</h3><span className="pill">{mine.length} submitted</span></div>{mine.length?<table><thead><tr><th>Date</th><th>Affected Periods</th><th>Reason</th><th>Status</th></tr></thead><tbody>{mine.map(x=><tr key={x.id}><td>{x.day}</td><td>{x.items.map(i=>i.period).join(", ")}</td><td>{x.reason}</td><td><span className={x.status==="Assigned"?"present":"pill"}>{x.status}</span></td></tr>)}</tbody></table>:<div className="chat-empty"><div>📩</div><b>No requests yet</b><span>Your submitted unavailability requests will appear here.</span></div>}</div></>;
}

function StaffRequests({s}){
 const pending=s.availabilityRequests.filter(x=>x.status==="Pending");
 const findBest=(req,item)=>{const original=s.teachers.find(t=>t.name===req.teacher)||s.teachers[0];const candidates=s.teachers.filter(t=>t.name!==req.teacher).map(t=>{const busy=s.substitutions.some(x=>x.substitute===t.name&&x.day===req.day&&x.period===item.period);const subjectMatch=t.subject===item.subject||t.subject.split(" / ").includes(item.subject);return {...t,busy,subjectMatch}}).sort((a,b)=>Number(b.subjectMatch)-Number(a.subjectMatch)||Number(a.busy)-Number(b.busy));return candidates.find(t=>!t.busy)||candidates[0]};
 const assign=req=>{const newItems=req.items.map(item=>{const best=findBest(req,item);return best?{id:Date.now()+Math.random(),day:req.day,period:item.period,original:req.teacher,subject:item.subject,classes:item.classes,reason:req.reason,substitute:best.name,status:"Assigned"}:null}).filter(Boolean);if(!newItems.length)return s.notify("No available substitute found");const next=[...s.substitutions,...newItems];s.setSubstitutions(next);s.setAvailabilityRequests(s.availabilityRequests.map(x=>x.id===req.id?{...x,status:"Assigned",assignedIds:newItems.map(i=>i.id)}:x));s.notify(`${newItems.map(x=>x.substitute).join(", ")} assigned and notified`)};
 const reject=req=>{s.setAvailabilityRequests(s.availabilityRequests.map(x=>x.id===req.id?{...x,status:"Rejected"}:x));s.notify("Request marked as rejected")};
 return <><PageTools title="Staff Requests" sub="Review teacher unavailability reports and arrange cover before assigning a substitute."/><div className="tt-banner">🔔 <b>Admin action:</b> teacher reports first → Admin reviews → Auto Find Substitute → assignment appears on the substitute teacher portal.</div><div className="grid2"><Card title="Request Summary"><div className="details"><span>Pending<b>{pending.length}</b></span><span>Assigned<b>{s.availabilityRequests.filter(x=>x.status==="Assigned").length}</b></span><span>Total Requests<b>{s.availabilityRequests.length}</b></span><span>Substitutions<b>{s.substitutions.length}</b></span></div></Card><Card title="Admin Workflow"><Activity text="1. Receive teacher request" time="Teacher portal"/><Activity text="2. Review affected period" time="Class + subject"/><Activity text="3. Auto Find Substitute" time="Free-period priority"/><Activity text="4. Assign & notify" time="Teacher portal"/></Card></div><div className="card"><div className="card-head"><h3>Unavailability Requests</h3><span className="pill">{pending.length} pending</span></div>{s.availabilityRequests.length?<table><thead><tr><th>Teacher</th><th>Date</th><th>Affected Classes</th><th>Reason</th><th>Status / Action</th></tr></thead><tbody>{s.availabilityRequests.map(req=><tr key={req.id}><td><b>{req.teacher}</b></td><td>{req.day}</td><td>{req.items.map(i=><div key={i.period}>{i.period} · {i.classes} · {i.subject}</div>)}</td><td>{req.reason}{req.note&&<div className="muted">{req.note}</div>}</td><td>{req.status==="Pending"?<div className="row-actions"><button type="button" className="primary" onClick={()=>assign(req)}><RefreshCw size={15}/> Auto Find & Assign</button><button type="button" className="status" onClick={()=>reject(req)}>Reject</button></div>:<span className="present">{req.status}</span>}</td></tr>)}</tbody></table>:<div className="chat-empty"><div>🔔</div><b>No staff requests</b><span>When a teacher reports unavailability, the request will appear here.</span></div>}</div></>;
}

function SubstitutionPlanner({s}){
 const [teacher,setTeacher]=useState("Priya Sharma"),[period,setPeriod]=useState("02:00 PM"),[day,setDay]=useState("Today"),[reason,setReason]=useState("Health issue / emergency"),[open,setOpen]=useState(false);
 const active=s.teachers.find(t=>t.name===teacher)||s.teachers[0];
 const candidates=s.teachers.filter(t=>t.name!==teacher).map(t=>{const busy=s.substitutions.some(x=>x.substitute===t.name&&x.day===day&&x.period===period);const subjectMatch=t.subject.split(" /").some(v=>v===active.subject)||t.subject===active.subject;return {...t,busy,subjectMatch}}).sort((a,b)=>Number(b.subjectMatch)-Number(a.subjectMatch)||Number(a.busy)-Number(b.busy));
 const best=candidates.find(t=>!t.busy)||candidates[0];
 const create=()=>{if(!best)return;const item={id:Date.now(),day,period,original:teacher,subject:active.subject,classes:active.classes.split(" / ")[0],reason,substitute:best.name,status:"Assigned"};s.setSubstitutions([...s.substitutions,item]);s.notify(`Auto-assigned ${best.name} for ${active.subject}`);setOpen(false)};
 return <><PageTools title="Staff Substitution" sub="Admin can also manually arrange cover for exceptional cases." action={()=>setOpen(true)} actionText="＋ Manual Arrange"/><div className="tt-banner">🤖 <b>Smart Substitute Planner:</b> normal flow starts with a teacher request. This page is an Admin fallback for urgent cases.</div><div className="card"><div className="card-head"><h3>Substitution Schedule</h3><span className="pill">{s.substitutions.length} assignments</span></div>{s.substitutions.length?<table><thead><tr><th>Period</th><th>Original Teacher</th><th>Class / Subject</th><th>Reason</th><th>Substitute</th><th>Status</th></tr></thead><tbody>{s.substitutions.map(x=><tr key={x.id}><td>{x.day} · {x.period}</td><td><b>{x.original}</b></td><td>{x.classes} · {x.subject}</td><td>{x.reason}</td><td><b>{x.substitute}</b></td><td><span className="present">{x.status}</span></td></tr>)}</tbody></table>:<div className="chat-empty"><div>🔄</div><b>No substitutions scheduled</b><span>Teacher requests will create assignments here after Admin approval.</span></div>}</div>{open&&<Modal title="Manual Emergency Substitute" onClose={()=>setOpen(false)}><form className="formgrid" onSubmit={e=>{e.preventDefault();create()}}><label>Unavailable Teacher<select value={teacher} onChange={e=>setTeacher(e.target.value)}>{s.teachers.map(t=><option key={t.name}>{t.name}</option>)}</select></label><label>Period<select value={period} onChange={e=>setPeriod(e.target.value)}><option>01:00 PM</option><option>02:00 PM</option><option>02:45 PM</option><option>03:30 PM</option></select></label><label>Date / Day<select value={day} onChange={e=>setDay(e.target.value)}><option>Today</option><option>Tomorrow</option></select></label><label>Reason<select value={reason} onChange={e=>setReason(e.target.value)}><option>Health issue / emergency</option><option>Staff meeting</option><option>Half-day leave</option><option>Personal work</option></select></label><div className="substitute-preview"><AlertTriangle size={18}/><div><b>Automatic recommendation</b><span>{best?`${best.name} · ${best.subject} · ${best.busy?"May have a conflict":"Free period"}`:"No available teacher"}</span></div></div><button className="primary" disabled={!best}><RefreshCw size={16}/> Auto Assign & Notify</button></form></Modal>}</>}
function SubstitutionDuty({u,s}){const duties=s.substitutions.filter(x=>x.substitute===u.name);return <><PageTools title="Substitution Duty" sub="Classes assigned to you when another teacher is unavailable."/><div className="tt-banner">🔔 <b>Teacher notification:</b> substitution duties are added separately from your regular timetable.</div>{duties.length?<div className="homework-grid">{duties.map(x=><div className="card" key={x.id}><span className="pill">{x.status}</span><h3>{x.subject} · {x.classes}</h3><p>{x.day} · {x.period}</p><p className="muted">Original teacher: {x.original}</p><p className="muted">Reason: {x.reason}</p><button type="button" className="primary" onClick={()=>s.notify(`Opening ${x.classes} substitution class`)}>Open Class</button></div>)}</div>:<div className="card"><div className="chat-empty"><div>✓</div><b>No substitution duty</b><span>You have no extra class assigned at the moment.</span></div></div>}</>}

function Chat({role,u,s}){
 const [text,setText]=useState("");
 const isTeacher=role==="Teacher";
 const [lastSeen,setLastSeen]=useState(()=>load("bf_chat_seen_"+(isTeacher?"teacher":"parent"),0));
 useEffect(()=>{
   const sync=()=>s.setChatMessages(load("bf_chat_v3",initialChatMessages));
   window.addEventListener("storage",sync);
   const channel="BroadcastChannel" in window ? new BroadcastChannel("bright-future-school-chat") : null;
   if(channel) channel.onmessage=sync;
   const timer=setInterval(sync,500);
   return()=>{window.removeEventListener("storage",sync);if(channel)channel.close();clearInterval(timer)};
 },[]);
 useEffect(()=>{
   const relevant=s.chatMessages.filter(m=>m.from!==(isTeacher?"teacher":"parent"));
   const seen=load("bf_chat_seen_"+(isTeacher?"teacher":"parent"),0);
   if(relevant.length>seen){setLastSeen(relevant.length)}
 },[s.chatMessages.length,isTeacher]);
 const send=()=>{
   if(!text.trim())return s.notify("Type a message first");
   const msg={id:Date.now(),from:isTeacher?"teacher":"parent",name:u.name,text:text.trim(),time:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})};
   const next=[...s.chatMessages,msg];
   s.setChatMessages(next);save("bf_chat_v3",next);
   if("BroadcastChannel" in window){const channel=new BroadcastChannel("bright-future-school-chat");channel.postMessage(msg);channel.close()}
   setText("");s.notify(isTeacher?"Reply sent to Priya Devi":"Message sent to Priya Sharma");
 };
 const contactName=isTeacher?"Priya Devi":"Priya Sharma";
 const contactSub=isTeacher?"Parent of Ananya Priya · Grade 3-A":"Class Teacher · Grade 3-A";
 const otherMessages=s.chatMessages.filter(m=>m.from!==(isTeacher?"teacher":"parent"));
 const unread=Math.max(0,otherMessages.length-lastSeen);
 return <div className="chat">
   <div className="chat-list">
     <div className="chat-list-title"><h3>{isTeacher?"Parent Messages":"Teacher Messages"}</h3>{unread>0&&<span className="chat-unread">{unread} new</span>}</div>
     <button type="button" className="chat-person active"><div className="avatar">{isTeacher?"P":"T"}</div><div><b>{contactName}</b><small>{contactSub}</small></div></button>
     <div className="chat-info">💬 <b>{s.chatMessages.length?"Conversation active":"No messages yet"}</b><br/><span>{isTeacher?"Messages sent by the parent appear here. Reply directly to continue the conversation.":"Send a message to your child's class teacher. The teacher can see it in Parent Messages."}</span></div>
   </div>
   <div className="chat-main">
     <div className="chat-head"><div className="avatar">{isTeacher?"P":"T"}</div><div><b>{contactName}</b><small className="chat-sub">{contactSub}</small></div><span className="chat-online">● Connected</span></div>
     <div className="messages">
       {!s.chatMessages.length&&<div className="chat-empty"><div>💬</div><b>Start the conversation</b><span>{isTeacher?"When a parent sends a message, it will appear here.":"Ask your child's teacher about homework, attendance or progress."}</span></div>}
       {s.chatMessages.map((m,i)=><div key={m.id||i} className={"bubble "+((m.from===(isTeacher?"teacher":"parent"))?"me":"other")}><small>{m.name} · {m.time}</small><div>{m.text}</div></div>)}
     </div>
     <div className="chat-input"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder={isTeacher?"Reply to Priya Devi...":"Message Priya Sharma..."}/><button type="button" className="primary" onClick={send}><Send size={16}/> {isTeacher?"Reply":"Send"}</button></div>
   </div>
 </div>
}
function Child({u,s}){const child=s.students.find(x=>x.name===u?.child)||s.students[0];return <><div className="welcome"><div><h1>{child?.name||u?.child}</h1><p>{child?.className||"Grade 3-A"} · Roll No. {child?.roll||"—"}</p></div><span className="pill">Active Student</span></div><div className="stats"><Stat title="Attendance" value={child?.attendance||"—"} sub="Current" icon={ClipboardCheck}/><Stat title="Average" value="91%" sub="Unit Test 1" icon={FileText}/><Stat title="Homework" value={s.homeworkItems.length} sub="Shared assignments" icon={BookOpen}/></div><div className="card"><h3>Student Details</h3><div className="details"><span>Parent <b>{child?.parent||u?.name}</b></span><span>Class Teacher <b>Priya Sharma</b></span><span>Admission No. <b>BF2026-{child?.roll||"0032"}</b></span><span>Class <b>{child?.className||"Grade 3-A"}</b></span></div></div></>}

function UsersPage({s}){const [users,setUsers]=useState(()=>load("bf_users",[accounts.admin,...teacherAccounts,accounts.parent]));const add=()=>{const name=prompt("New user name:");if(!name)return;const next=[...users,{name,email:name.toLowerCase().replaceAll(" ",".")+"@school.demo",role:"Teacher"}];setUsers(next);save("bf_users",next);s.notify("User added successfully")};return <><PageTools title="User Management" sub="Demo login accounts and role access." action={add} actionText="＋ Add User"/><div className="card"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th></tr></thead><tbody>{users.map(a=><tr key={a.email}><td><b>{a.name}</b></td><td>{a.email}</td><td><span className="pill">{a.role}</span></td><td><span className="present">Active</span></td></tr>)}</tbody></table></div></>}
function Reports({s}){const exportReport=()=>{const data=["Bright Future Primary School Report","Students: "+s.students.length,"Teachers: "+s.teachers.length,"Homework: "+s.homeworkItems.length,"Notices: "+s.notices.length].join("\n");const blob=new Blob([data],{type:"text/plain"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="school-report.txt";a.click();URL.revokeObjectURL(a.href);s.notify("Report exported")};return <><PageTools title="Reports" sub="Quick school performance reports." action={exportReport} actionText="Export Report"/><div className="report-grid">{[["Student Strength",s.students.length,"Active records"],["Attendance","94.6%","School average"],["Academic Average","88.4%","Unit Test 1"],["Fee Collection","82%","Monthly target"]].map(x=><div className="report-box" key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong><span>{x[2]}</span><div className="bar"><i style={{width:"78%"}}></i></div></div>)}</div></>}
function SettingsPage({s}){const [name,setName]=useState(()=>load("bf_school_name","Bright Future Primary School"));return <><PageTools title="Settings" sub="School profile and preferences." action={()=>{save("bf_school_name",name);s.notify("Settings saved successfully")}} actionText="Save Changes"/><div className="card formgrid"><label>School Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Academic Year<input defaultValue="2026 – 2027"/></label><label>School Phone<input defaultValue="+91 98765 43210"/></label><label>Email<input defaultValue="office@brightfuture.demo"/></label></div></>}
function Leave({s}){const [requests,setRequests]=useState(()=>load("bf_leave",[]));const request=()=>{const next=[...requests,{type:"Casual Leave",date:"Sep 18",reason:"Personal work",status:"Pending"}];setRequests(next);save("bf_leave",next);s.notify("Leave request submitted successfully")};return <><PageTools title="Leave Request" sub="Submit and track your leave requests." action={request} actionText="＋ Request Leave"/><div className="card"><table><thead><tr><th>Type</th><th>Dates</th><th>Reason</th><th>Status</th></tr></thead><tbody>{requests.length?requests.map((x,i)=><tr key={i}><td>{x.type}</td><td>{x.date}</td><td>{x.reason}</td><td><span className="pending">{x.status}</span></td></tr>):<tr><td colSpan="4">No leave requests yet. Click Request Leave to add one.</td></tr>}</tbody></table></div></>}
function Profile({u,s}){const [name,setName]=useState(u.name);return <><div className="profile-card"><div className="avatar huge">{name[0]}</div><h1>{name}</h1><p>{u.role} · Bright Future Primary School</p><div className="details"><span>Email <b>{u.email}</b></span><span>Role <b>{u.role}</b></span><span>Phone <b>+91 98765 43210</b></span></div><button type="button" className="primary" onClick={()=>s.notify("Profile saved for "+name)}>Save Profile</button><button type="button" className="secondary" onClick={()=>{const n=prompt("Enter display name",name);if(n){setName(n);s.notify("Profile name updated")}}}>Edit Profile</button></div></>}
function PageTools({title,sub,action,actionText}){return <div className="page-tools"><div><h1>{title}</h1><p className="muted">{sub}</p></div>{action&&<button type="button" className="primary" onClick={action}><Plus size={17}/>{actionText.replace("＋","")}</button>}</div>}

createRoot(document.getElementById("root")).render(<App/>);
