import React,{useEffect,useState} from "react";
import {Wallet,Bell,CheckCircle2,Send,AlertTriangle,TrendingUp,TrendingDown,Phone} from "lucide-react";
import {Card,Modal,PageTools,Stat} from "../../components/ui";
import {FeeHeads} from "./FeeHeads";
import {FeeReports} from "./FeeReports";
import {SmartPay,defaultFeeHeads} from "./SmartPay";
import {StudentFees} from "./StudentFees";
import {daysBetween,fmt,todayISO} from "../../utils/format";
import {load,save} from "../../utils/storage";

const initialFeeRecords=[
 {id:1,student:"Aarav Kumar",className:"Grade 3-A",parent:"Kumar Raj",phone:"98400 11001",head:"Tuition Fee – Term 1",amount:12000,due:"2026-06-10",status:"Paid",lastFollowup:""},
 {id:2,student:"Aarav Kumar",className:"Grade 3-A",parent:"Kumar Raj",phone:"98400 11001",head:"Tuition Fee – Term 2",amount:12000,due:"2026-09-10",status:"Paid",lastFollowup:""},
 {id:3,student:"Aarav Kumar",className:"Grade 3-A",parent:"Kumar Raj",phone:"98400 11001",head:"Transport Fee",amount:4000,due:"2026-09-10",status:"Paid",lastFollowup:""},
 {id:4,student:"Aarav Kumar",className:"Grade 3-A",parent:"Kumar Raj",phone:"98400 11001",head:"Activity Fee",amount:2000,due:"2026-10-10",status:"Pending",lastFollowup:""},
 {id:5,student:"Ananya Priya",className:"Grade 3-A",parent:"Priya Devi",phone:"98400 11002",head:"Tuition Fee – Term 1",amount:12000,due:"2026-06-10",status:"Paid",lastFollowup:""},
 {id:6,student:"Ananya Priya",className:"Grade 3-A",parent:"Priya Devi",phone:"98400 11002",head:"Tuition Fee – Term 2",amount:12000,due:"2026-09-05",status:"Pending",lastFollowup:"2026-09-08"},
 {id:7,student:"Ananya Priya",className:"Grade 3-A",parent:"Priya Devi",phone:"98400 11002",head:"Books & Uniform",amount:3500,due:"2026-06-15",status:"Paid",lastFollowup:""},
 {id:8,student:"Dhruv Anand",className:"Grade 4-B",parent:"Anand S",phone:"98400 11003",head:"Tuition Fee – Term 1",amount:12000,due:"2026-06-10",status:"Paid",lastFollowup:""},
 {id:9,student:"Dhruv Anand",className:"Grade 4-B",parent:"Anand S",phone:"98400 11003",head:"Tuition Fee – Term 2",amount:12000,due:"2026-09-10",status:"Pending",lastFollowup:""},
 {id:10,student:"Dhruv Anand",className:"Grade 4-B",parent:"Anand S",phone:"98400 11003",head:"Transport Fee",amount:4000,due:"2026-08-30",status:"Pending",lastFollowup:""},
 {id:11,student:"Ishita Rao",className:"Grade 5-A",parent:"Rao Meena",phone:"98400 11004",head:"Tuition Fee – Term 1",amount:12000,due:"2026-06-10",status:"Paid",lastFollowup:""},
 {id:12,student:"Ishita Rao",className:"Grade 5-A",parent:"Rao Meena",phone:"98400 11004",head:"Tuition Fee – Term 2",amount:12000,due:"2026-09-10",status:"Paid",lastFollowup:""},
 {id:13,student:"Ishita Rao",className:"Grade 5-A",parent:"Rao Meena",phone:"98400 11004",head:"Activity Fee",amount:2000,due:"2026-09-20",status:"Pending",lastFollowup:""},
 {id:14,student:"Vihaan Raj",className:"Grade 2-B",parent:"Kumar Raj",phone:"98400 11005",head:"Tuition Fee – Term 1",amount:12000,due:"2026-06-10",status:"Paid",lastFollowup:""},
 {id:15,student:"Vihaan Raj",className:"Grade 2-B",parent:"Kumar Raj",phone:"98400 11005",head:"Tuition Fee – Term 2",amount:12000,due:"2026-09-01",status:"Pending",lastFollowup:"2026-09-03"}
];
const admissionStages=["Enquiry","Application","Registration","Evaluation","Confirmed"];
const initialAdmissions=[
 {id:1,child:"Rohan Selvam",age:6,grade:"Grade 1-A",parent:"Selvam K",phone:"98400 22001",stage:"Enquiry",nextFollowup:"2026-09-09",note:"Asked about transport",created:"2026-09-06"},
 {id:2,child:"Meera Krishnan",age:7,grade:"Grade 2-B",parent:"Krishnan R",phone:"98400 22002",stage:"Application",nextFollowup:"2026-09-11",note:"Documents pending",created:"2026-09-02",outcome:"Positive",reason:"Parent very interested"},
 {id:5,child:"Karthik Mohan",age:7,grade:"Grade 2-B",parent:"Mohan L",phone:"98400 22005",stage:"Enquiry",nextFollowup:"",note:"Fee too high for them",created:"2026-08-25",outcome:"Negative",reason:"Fee budget / joined another school"},
 {id:3,child:"Adhav Prasanna",age:8,grade:"Grade 3-A",parent:"Prasanna V",phone:"98400 22003",stage:"Evaluation",nextFollowup:"2026-09-12",note:"Interaction scheduled",created:"2026-08-28"},
 {id:4,child:"Sana Fathima",age:6,grade:"Grade 1-A",parent:"Fathima B",phone:"98400 22004",stage:"Confirmed",nextFollowup:"",note:"Admission fee paid",created:"2026-08-20",outcome:"Positive",reason:"Admitted"}
];
function followupFor(rec,kind){const t=todayISO();if(kind==="fee"){if(rec.status==="Paid")return null;const overdue=daysBetween(t,rec.due);const sinceLast=rec.lastFollowup?daysBetween(t,rec.lastFollowup):99;if(overdue>7&&sinceLast>=2)return {level:"high",text:`Overdue ${overdue} days · Call parent`,channel:"Call"};if(overdue>0&&sinceLast>=3)return {level:"high",text:`Overdue ${overdue} days · Send WhatsApp`,channel:"WhatsApp"};if(overdue>=-3&&overdue<=0&&sinceLast>=3)return {level:"medium",text:`Due in ${-overdue} day(s) · Gentle reminder`,channel:"SMS"};if(sinceLast<3)return {level:"low",text:`Reminded ${sinceLast} day(s) ago · Wait`,channel:""};return {level:"low",text:"On track",channel:""}}
 if(rec.stage==="Confirmed"||rec.outcome==="Negative")return null;const d=rec.nextFollowup?daysBetween(t,rec.nextFollowup):0;const idle=daysBetween(t,rec.created);if(d>0)return {level:"high",text:`Follow-up missed by ${d} day(s) · Call now`,channel:"Call"};if(d===0)return {level:"medium",text:"Follow-up due today",channel:"Call"};if(idle>10)return {level:"medium",text:`No progress for ${idle} days · Nudge`,channel:"WhatsApp"};return {level:"low",text:`Next follow-up in ${-d} day(s)`,channel:""}}
function Fees({role,s,initialTab}){
 const [tab,setTab]=useState(initialTab||"fees");useEffect(()=>{if(initialTab)setTab(initialTab)},[initialTab]);const [heads,setHeads]=useState(()=>load("bf_fee_heads_v1",defaultFeeHeads));useEffect(()=>save("bf_fee_heads_v1",heads),[heads]);
 const [fees,setFees]=useState(()=>load("bf_fee_records_v2",initialFeeRecords));
 const [adm,setAdm]=useState(()=>load("bf_admissions_v2",initialAdmissions));
 useEffect(()=>save("bf_fee_records_v2",fees),[fees]);useEffect(()=>save("bf_admissions_v2",adm),[adm]);
 const total=fees.reduce((a,f)=>a+f.amount,0),paid=fees.filter(f=>f.status==="Paid").reduce((a,f)=>a+f.amount,0),pending=total-paid;
 const feeAlerts=fees.map(f=>({f,fu:followupFor(f,"fee")})).filter(x=>x.fu&&x.fu.level!=="low");
 const admAlerts=adm.map(a=>({a,fu:followupFor(a,"adm")})).filter(x=>x.fu&&x.fu.level!=="low");
 const markPaid=id=>{setFees(fees.map(f=>f.id===id?{...f,status:"Paid"}:f));s.notify("Payment recorded & receipt generated")};
 const remind=(id,ch)=>{setFees(fees.map(f=>f.id===id?{...f,lastFollowup:todayISO()}:f));s.notify((ch||"Reminder")+" reminder sent to parent")};
 const addFee=()=>s.setModal(<FeeForm s={s} onSave={r=>{setFees([...fees,{...r,id:Date.now(),status:"Pending",lastFollowup:""}]);s.setModal(null);s.notify("Fee demand created")}} onClose={()=>s.setModal(null)}/>);
 const addAdm=()=>s.setModal(<AdmissionForm s={s} onSave={r=>{setAdm([...adm,{...r,id:Date.now(),stage:"Enquiry",created:todayISO()}]);s.setModal(null);s.notify("Enquiry added to admission pipeline")}} onClose={()=>s.setModal(null)}/>);
 const advance=id=>{setAdm(adm.map(a=>{if(a.id!==id)return a;const i=admissionStages.indexOf(a.stage);const stage=admissionStages[Math.min(i+1,admissionStages.length-1)];const nf=new Date();nf.setDate(nf.getDate()+3);return {...a,stage,nextFollowup:stage==="Confirmed"?"":nf.toISOString().slice(0,10)}}));s.notify("Moved to next stage")};
 const setOutcome=(id,outcome)=>{const reason=outcome==="Negative"?prompt("Reason for negative response (e.g. fee, distance, joined other school):","Fee budget"):prompt("Positive note:","Parent interested, will visit");if(reason===null)return;setAdm(adm.map(a=>a.id===id?{...a,outcome,reason}:a));s.notify("Enquiry marked "+outcome)};
 const admDone=(id,ch)=>{const nf=new Date();nf.setDate(nf.getDate()+3);setAdm(adm.map(a=>a.id===id?{...a,nextFollowup:nf.toISOString().slice(0,10)}:a));s.notify((ch||"Follow-up")+" done · next follow-up in 3 days")};
 const Level=({l})=><span className={"status "+(l.level==="high"?"neg":l.level==="medium"?"pending":"")}>{l.text}</span>;
 return <><PageTools title="Fees & Admission" sub="Fee collection, admission pipeline and smart follow-ups." action={tab==="admission"?addAdm:tab==="fees"?addFee:null} actionText={tab==="admission"?"New Enquiry":"New Fee Demand"}/>
 <div className="tabs">{[["fees","Fees"],["students","Student-wise"],["smartpay","Smart Pay"],["heads","Fee Heads"],["reports","Fee Reports"],["admission","Admission"],["followup","Smart Follow-up"+(feeAlerts.length+admAlerts.length?` (${feeAlerts.length+admAlerts.length})`:"")]].map(([k,l])=><button type="button" key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{l}</button>)}</div>
 {tab==="fees"&&<><div className="stats"><Stat title="Total Demand" value={fmt(total)} sub={fees.length+" fee records"} icon={Wallet}/><Stat title="Collected" value={fmt(paid)} sub={Math.round(paid/total*100||0)+"% collected"} icon={CheckCircle2}/><Stat title="Pending" value={fmt(pending)} sub={fees.filter(f=>f.status!=="Paid").length+" students"} icon={AlertTriangle}/><Stat title="Overdue" value={fees.filter(f=>f.status!=="Paid"&&daysBetween(todayISO(),f.due)>0).length} sub="Need follow-up" icon={Bell}/></div>
 <div className="card"><table><thead><tr><th>Student</th><th>Fee Head</th><th>Amount</th><th>Due</th><th>Status</th><th>Smart Follow-up</th><th>Action</th></tr></thead><tbody>{fees.map(f=>{const fu=followupFor(f,"fee");return <tr key={f.id}><td><b>{f.student}</b><br/><small className="muted">{f.className} · {f.parent}</small></td><td>{f.head}</td><td>{fmt(f.amount)}</td><td>{f.due}</td><td><span className={f.status==="Paid"?"present":"pending"}>{f.status}</span></td><td>{fu?<Level l={fu}/>:<span className="muted">—</span>}</td><td>{f.status==="Paid"?<button type="button" className="link" onClick={()=>s.notify("Receipt downloaded")}>Receipt</button>:<><button type="button" className="link" onClick={()=>markPaid(f.id)}>Mark Paid</button> <button type="button" className="link" onClick={()=>remind(f.id,fu?.channel)}>Remind</button></>}</td></tr>})}</tbody></table></div></>}
 {tab==="students"&&<StudentFees s={s} fees={fees} heads={heads} setTab={setTab}/>}
 {tab==="smartpay"&&<SmartPay s={s} heads={heads} fees={fees} setFees={setFees}/>}
 {tab==="heads"&&<FeeHeads s={s} heads={heads} setHeads={setHeads}/>}
 {tab==="reports"&&<FeeReports s={s} fees={fees}/>}
 {tab==="admission"&&<><div className="pipeline">{admissionStages.map(st=><div className="pipe" key={st}><b>{adm.filter(a=>a.stage===st).length}</b><span>{st}</span></div>)}</div>
 <div className="pn" style={{marginBottom:18}}><div className="pn-col pos"><h4><TrendingUp size={15}/> Positive Enquiries</h4><strong>{adm.filter(a=>a.outcome==="Positive").length} <small style={{fontSize:12,fontWeight:600}}>of {adm.length}</small></strong>{adm.filter(a=>a.outcome==="Positive").map(a=><div className="pn-row" key={a.id}><span>{a.child} · {a.grade}</span><b>{a.reason||a.stage}</b></div>)}{!adm.some(a=>a.outcome==="Positive")&&<small className="muted">None yet</small>}</div><div className="pn-col neg"><h4><TrendingDown size={15}/> Negative Enquiries</h4><strong>{adm.filter(a=>a.outcome==="Negative").length} <small style={{fontSize:12,fontWeight:600}}>of {adm.length}</small></strong>{adm.filter(a=>a.outcome==="Negative").map(a=><div className="pn-row" key={a.id}><span>{a.child} · {a.grade}</span><b>{a.reason||"—"}</b></div>)}{!adm.some(a=>a.outcome==="Negative")&&<small className="muted">None yet</small>}</div></div>
 <div className="card"><table><thead><tr><th>Child</th><th>Grade</th><th>Parent</th><th>Stage</th><th>Response</th><th>Next Follow-up</th><th>Smart Follow-up</th><th>Action</th></tr></thead><tbody>{adm.map(a=>{const fu=followupFor(a,"adm");return <tr key={a.id}><td><b>{a.child}</b><br/><small className="muted">Age {a.age} · {a.note}</small></td><td>{a.grade}</td><td>{a.parent}<br/><small className="muted">{a.phone}</small></td><td><span className={a.stage==="Confirmed"?"present":"pill"}>{a.stage}</span></td><td><div className="pn-toggle"><button type="button" className={"pn-btn pos "+(a.outcome==="Positive"?"on":"")} onClick={()=>setOutcome(a.id,"Positive")} title="Positive">👍</button><button type="button" className={"pn-btn neg "+(a.outcome==="Negative"?"on":"")} onClick={()=>setOutcome(a.id,"Negative")} title="Negative">👎</button></div>{a.reason&&<small className={"muted "+(a.outcome==="Negative"?"txt-neg":"txt-pos")} style={{display:"block",fontSize:10,marginTop:4}}>{a.reason}</small>}</td><td>{a.nextFollowup||"—"}</td><td>{fu?<Level l={fu}/>:<span className={a.outcome==="Negative"?"status neg":"present"}>{a.outcome==="Negative"?"Closed":"Admitted"}</span>}</td><td>{a.stage!=="Confirmed"&&a.outcome!=="Negative"&&<><button type="button" className="link" onClick={()=>advance(a.id)}>Next Stage</button> <button type="button" className="link" onClick={()=>admDone(a.id,fu?.channel)}>Follow-up Done</button></>}</td></tr>})}</tbody></table></div></>}
 {tab==="followup"&&<div className="grid2"><Card title={`Fee Follow-ups (${feeAlerts.length})`}>{feeAlerts.length===0&&<p className="muted">No fee follow-ups needed right now 🎉</p>}{feeAlerts.map(({f,fu})=><div className="fu-row" key={f.id}><div><b>{f.parent}</b> <small className="muted">({f.student} · {f.className})</small><br/><small>{f.head} · {fmt(f.amount)} · Due {f.due}</small><br/><Level l={fu}/></div><div className="fu-actions"><button type="button" className="primary sm" onClick={()=>remind(f.id,fu.channel)}>{fu.channel==="Call"?<Phone size={14}/>:<Send size={14}/>}{fu.channel||"Remind"}</button><button type="button" className="link" onClick={()=>markPaid(f.id)}>Paid</button></div></div>)}</Card>
 <Card title={`Admission Follow-ups (${admAlerts.length})`}>{admAlerts.length===0&&<p className="muted">All enquiries are on track.</p>}{admAlerts.map(({a,fu})=><div className="fu-row" key={a.id}><div><b>{a.parent}</b> <small className="muted">({a.child} · {a.grade})</small><br/><small>Stage: {a.stage} · {a.phone}</small><br/><Level l={fu}/></div><div className="fu-actions"><button type="button" className="primary sm" onClick={()=>admDone(a.id,fu.channel)}>{fu.channel==="Call"?<Phone size={14}/>:<Send size={14}/>}{fu.channel||"Follow-up"}</button><button type="button" className="link" onClick={()=>advance(a.id)}>Advance</button></div></div>)}</Card>
 <Card title="How Smart Follow-up works"><ul className="rules"><li>Fees overdue &gt; 7 days → <b>Call</b> parent (every 2 days)</li><li>Fees overdue 1–7 days → <b>WhatsApp</b> reminder (every 3 days)</li><li>Fees due within 3 days → <b>SMS</b> gentle reminder</li><li>Admission follow-up date missed → <b>Call now</b></li><li>Enquiry idle &gt; 10 days → <b>Nudge</b> via WhatsApp</li></ul></Card></div>}
 </>}
function FeeForm({s,onSave,onClose}){const heads=load("bf_fee_heads_v1",defaultFeeHeads);const [f,setF]=useState({student:s.students[0]?.name||"",head:heads[0]?.name||"Tuition Fee",amount:heads[0]?.amount||12000,due:todayISO()});const st=s.students.find(x=>x.name===f.student)||{};const set=k=>e=>setF({...f,[k]:e.target.value});return <Modal title="New Fee Demand" onClose={onClose}><div className="formgrid"><label>Student<select value={f.student} onChange={set("student")}>{s.students.map(x=><option key={x.name}>{x.name}</option>)}</select></label><label>Fee Head<select value={f.head} onChange={e=>{const h=heads.find(x=>x.name===e.target.value);setF({...f,head:e.target.value,amount:h?h.amount:f.amount})}}>{heads.map(h=><option key={h.name}>{h.name}</option>)}</select></label><label>Amount (₹)<input type="number" value={f.amount} onChange={set("amount")}/></label><label>Due Date<input type="date" value={f.due} onChange={set("due")}/></label></div><button type="button" className="primary full" onClick={()=>onSave({...f,amount:Number(f.amount),className:st.className||"",parent:st.parent||"",phone:""})}>Save</button></Modal>}
function AdmissionForm({s,onSave,onClose}){const [f,setF]=useState({child:"",age:6,grade:s.classes[0]||"Grade 1-A",parent:"",phone:"",note:"",nextFollowup:todayISO()});const set=k=>e=>setF({...f,[k]:e.target.value});return <Modal title="New Admission Enquiry" onClose={onClose}><div className="formgrid"><label>Child Name<input value={f.child} onChange={set("child")}/></label><label>Age<input type="number" value={f.age} onChange={set("age")}/></label><label>Grade Applying<select value={f.grade} onChange={set("grade")}>{s.classes.map(c=><option key={c}>{c}</option>)}</select></label><label>Parent Name<input value={f.parent} onChange={set("parent")}/></label><label>Phone<input value={f.phone} onChange={set("phone")}/></label><label>Next Follow-up<input type="date" value={f.nextFollowup} onChange={set("nextFollowup")}/></label><label>Note<input value={f.note} onChange={set("note")}/></label></div><button type="button" className="primary full" onClick={()=>{if(!f.child||!f.parent)return s.notify("Child and parent name required");onSave({...f,age:Number(f.age)})}}>Add Enquiry</button></Modal>}

export {initialFeeRecords,admissionStages,initialAdmissions,followupFor,Fees,FeeForm,AdmissionForm};
