import React,{useState} from "react";
import {Users,Wallet,CheckCircle2,Download,AlertTriangle,CreditCard} from "lucide-react";
import {Stat} from "../../components/ui";
import {daysBetween,fmt,todayISO} from "../../utils/format";

function StudentFees({s,fees,heads,setTab}){
 const [open,setOpen]=useState(null);const [cls,setCls]=useState("All");
 const rows=s.students.filter(st=>cls==="All"||st.className===cls).map(st=>{const fs=fees.filter(f=>f.student===st.name);const total=fs.reduce((a,f)=>a+f.amount,0);const paid=fs.filter(f=>f.status==="Paid").reduce((a,f)=>a+f.amount,0);const pending=total-paid;const overdue=fs.filter(f=>f.status!=="Paid"&&daysBetween(todayISO(),f.due)>0).length;return {st,fs,total,paid,pending,pct:total?Math.round(paid/total*100):0,overdue}});
 const T=rows.reduce((a,r)=>({total:a.total+r.total,paid:a.paid+r.paid,pending:a.pending+r.pending}),{total:0,paid:0,pending:0});
 return <>
  <div className="stats"><Stat title="Students" value={rows.length} sub={rows.filter(r=>r.pending===0).length+" fully paid"} icon={Users}/><Stat title="Total Fee" value={fmt(T.total)} sub="Annual demand" icon={Wallet}/><Stat title="Paid" value={fmt(T.paid)} sub={(T.total?Math.round(T.paid/T.total*100):0)+"% collected"} icon={CheckCircle2}/><Stat title="Pending" value={fmt(T.pending)} sub={rows.filter(r=>r.pending>0).length+" students with balance"} icon={AlertTriangle}/></div>
  <div className="card"><div className="card-head"><h3>Student-wise Fee Structure</h3><select value={cls} onChange={e=>setCls(e.target.value)}><option>All</option>{s.classes.map(c=><option key={c}>{c}</option>)}</select></div>
  <table><thead><tr><th>Student</th><th>Class</th><th>Parent</th><th>Total Fee</th><th>Paid</th><th>Pending</th><th>Progress</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(r=><React.Fragment key={r.st.name}><tr><td><b>{r.st.name}</b></td><td>{r.st.className}</td><td>{r.st.parent}</td><td>{fmt(r.total)}</td><td className="txt-pos">{fmt(r.paid)}</td><td className={r.pending?"txt-neg":"muted"}>{fmt(r.pending)}</td><td style={{minWidth:120}}><div className="bar" style={{marginTop:0}}><i style={{width:r.pct+"%",background:r.pct===100?"#16a34a":r.overdue?"#dc2626":"#3b82f6"}}></i></div><small className="muted">{r.pct}% paid</small></td><td>{r.pending===0?<span className="present">Fully Paid</span>:r.overdue?<span className="status neg">{r.overdue} overdue</span>:<span className="pending">Partial</span>}</td><td><button type="button" className="link" onClick={()=>setOpen(open===r.st.name?null:r.st.name)}>{open===r.st.name?"Hide":"Details"}</button></td></tr>
  {open===r.st.name&&<tr className="detail-row"><td colSpan={9}><div className="fee-detail"><div className="fee-detail-list">{r.fs.length===0&&<p className="muted">No fee demands created for this student.</p>}{r.fs.map(f=><div className="fee-line" key={f.id}><span className={"tx-sign "+(f.status==="Paid"?"pos":"neg")}>{f.status==="Paid"?"✓":"!"}</span><div><b>{f.head}</b><small>Due {f.due}{f.status!=="Paid"&&daysBetween(todayISO(),f.due)>0&&<span className="txt-neg"> · overdue {daysBetween(todayISO(),f.due)} days</span>}</small></div><b className={f.status==="Paid"?"txt-pos":"txt-neg"}>{fmt(f.amount)}</b><span className={f.status==="Paid"?"present":"pending"}>{f.status}</span></div>)}</div>
  <div className="fee-summary"><div><span>Total</span><b>{fmt(r.total)}</b></div><div><span>Paid</span><b className="txt-pos">{fmt(r.paid)}</b></div><div><span>Pending</span><b className="txt-neg">{fmt(r.pending)}</b></div>{r.pending>0&&<button type="button" className="primary sm" onClick={()=>setTab("smartpay")}><CreditCard size={13}/> Collect via Smart Pay</button>}<button type="button" className="link" onClick={()=>s.notify("Fee statement for "+r.st.name+" downloaded")}><Download size={13}/> Statement</button></div></div></td></tr>}</React.Fragment>)}</tbody>
  <tfoot><tr><td colSpan={3}><b>Total ({rows.length} students)</b></td><td><b>{fmt(T.total)}</b></td><td className="txt-pos"><b>{fmt(T.paid)}</b></td><td className="txt-neg"><b>{fmt(T.pending)}</b></td><td colSpan={3}><div className="bar" style={{marginTop:0}}><i style={{width:(T.total?Math.round(T.paid/T.total*100):0)+"%"}}></i></div></td></tr></tfoot></table></div>
 </>}

export {StudentFees};
