import React from "react";
import {Users,GraduationCap,BookOpen,ClipboardCheck,Wallet,Clock} from "lucide-react";
import {Activity,Card,Modal,Stat,Task,TimeRows} from "../components/ui";
import {defaultTT} from "../data/seed";
import {NoticeForm} from "./Notices";
import {TeacherForm} from "./Teachers";

function Dashboard({u,s}){const r=u.role;const go=p=>{s.setPage(p);s.notify("Opening "+p);};if(r==="Admin")return <><div className="welcome"><div><h1>School Overview</h1><p>Manage your primary school from one place.</p></div><button type="button" className="primary" onClick={()=>s.setModal(<QuickAction s={s} onClose={()=>s.setModal(null)}/>)}>+ Quick Action</button></div><div className="stats"><Stat title="Total Students" value={s.students.length} sub="Active records" icon={Users} onClick={()=>go("Students")}/><Stat title="Teachers" value={s.teachers.length} sub="Active staff" icon={GraduationCap} onClick={()=>go("Teachers")}/><Stat title="Attendance Today" value="94.6%" sub="School average" icon={ClipboardCheck} onClick={()=>go("Attendance")}/><Stat title="Fees Collected" value="₹8.4L" sub="82% of monthly target" icon={Wallet} onClick={()=>go("Fees")}/></div><div className="grid2"><Card title="Today's Highlights"><Activity text="Class 3-A Mathematics" time="Priya Sharma · 09:00 AM"/><Activity text="Inter-house Quiz" time="School Auditorium · 02:00 PM"/><Activity text="Parent Meeting" time="Saturday · 10:00 AM"/></Card><Card title="Recent Activity"><Activity text={s.homeworkItems.length+" homework assignments available"} time="Live data"/><Activity text={s.students.length+" student records"} time="Live data"/><Activity text={s.notices.length+" notices published"} time="Live data"/></Card></div></>;
 if(r==="Teacher")return <><div className="welcome"><div><h1>Teacher Dashboard</h1><p>Your classes and daily teaching tasks.</p></div><button type="button" className="pill" onClick={()=>go("My Timetable")}>{u.name} · {s.teachers.find(t=>t.name===u.name)?.subject||"Teacher"}</button></div><div className="stats"><Stat title="My Students" value={s.students.length} sub="Grade 3-A" icon={Users} onClick={()=>go("My Students")}/><Stat title="Today's Classes" value="4" sub="Next at 10:00 AM" icon={Clock} onClick={()=>go("My Timetable")}/><Stat title="Attendance" value="96%" sub="This month" icon={ClipboardCheck} onClick={()=>go("Attendance")}/><Stat title="Pending Tasks" value={s.homeworkItems.filter(x=>!x.completed).length} sub="Homework" icon={BookOpen} onClick={()=>go("Homework")}/></div><div className="grid2"><Card title="Today's Timetable"><TimeRows rows={defaultTT.filter(x=>x[0]==="Monday").slice(0,3)}/></Card><Card title="My Tasks"><Task text="Mark Grade 3-A attendance" onClick={()=>go("Attendance")}/><Task text="Review Maths homework" onClick={()=>go("Homework")}/><Task text="Enter Unit Test marks" onClick={()=>go("Enter Marks")}/><Task text="Submit leave request" onClick={()=>go("Leave Request")}/></Card></div></>;
 if(r==="Parent")return <><div className="welcome"><div><h1>Hello, {u.name} 👋</h1><p>Here is your child's school progress.</p></div><button type="button" className="pill" onClick={()=>go("My Child")}>Child · Ananya Priya</button></div><div className="stats"><Stat title="Attendance" value="98%" sub="Excellent attendance" icon={ClipboardCheck} onClick={()=>go("Attendance")}/><Stat title="Average Marks" value="91%" sub="Unit Test 1" icon={FileText} onClick={()=>go("Marks / Report Card")}/><Stat title="Homework" value={s.homeworkItems.length} sub="Shared assignments" icon={BookOpen} onClick={()=>go("Homework")}/><Stat title="Fees" value="Paid" sub="Next due: Oct 10" icon={Wallet} onClick={()=>go("Fees & Payment")}/></div><div className="grid2"><Card title="Today's Timetable"><TimeRows rows={defaultTT.filter(x=>x[0]==="Monday").slice(0,3)}/></Card><Card title="Recent Updates"><Activity text="Mathematics homework assigned" time="Today, 9:15 AM"/><Activity text="Ananya marked Present" time="Today, 8:45 AM"/><Activity text="Unit Test marks published" time="Yesterday"/></Card></div></>;
 return null;
}

function QuickAction({s,onClose}){const [type,setType]=useState("homework");return <Modal title="Quick Action" onClose={onClose}><div className="formgrid"><label>Action<select value={type} onChange={e=>setType(e.target.value)}><option value="homework">Add Homework</option><option value="student">Add Student</option><option value="teacher">Add Teacher</option><option value="notice">New Notice</option></select></label><button className="primary" type="button" onClick={()=>{onClose();s.setModal(type==="homework"?<HomeworkForm s={s} onClose={()=>s.setModal(null)}/>:type==="student"?<StudentForm s={s} onClose={()=>s.setModal(null)}/>:type==="teacher"?<TeacherForm s={s} onClose={()=>s.setModal(null)}/>:<NoticeForm s={s} onClose={()=>s.setModal(null)}/>);}}>Continue</button></div></Modal>}

export {Dashboard,QuickAction};
