import React,{useState} from "react";
import {BookOpen,CheckCircle2,Search,Library} from "lucide-react";
import {Modal,PageTools,Stat} from "../components/ui";

function LibraryPage({role,s}){
 const canManage=role==="Admin"||role==="Teacher";
 const studentName=role==="Parent"?"Ananya Priya":"";
 const [q,setQ]=useState(""); const [cat,setCat]=useState("All");
 const [open,setOpen]=useState(false); const [borrowed,setBorrowed]=useState(false);
 const books=s.library||[];
 const filtered=books.filter(b=>(cat==="All"||b.category===cat)&&(b.title+b.author+b.category).toLowerCase().includes(q.toLowerCase()));
 const issue=id=>{const book=books.find(b=>b.id===id);if(!book||book.available<1)return s.notify("No copy available");const target=studentName||prompt("Enter student name to issue this book:","Aarav Kumar");if(!target||!target.trim())return s.notify("Student name is required");const next=books.map(b=>b.id===id?{...b,available:b.available-1,issuedTo:target.trim(),due:"Sep 20"}:b);s.setLibrary(next);setBorrowed(true);s.notify(book.title+" issued to "+target.trim())};
 const returnBook=id=>{const next=books.map(b=>b.id===id?{...b,available:Math.min(b.total,b.available+1),issuedTo:"",due:""}:b);s.setLibrary(next);s.notify("Book returned successfully")};
 const addBook=book=>{s.setLibrary([...books,{...book,id:Date.now()}]);setOpen(false);s.notify("Book added to library")};
 const myBooks=studentName?books.filter(b=>b.issuedTo===studentName):[];
 return <><PageTools title="Library Management" sub={canManage?"Manage books, issue and return records.":"Browse books and view your borrowed books."} action={canManage?()=>setOpen(true):null} actionText="＋ Add Book"/>
 <div className="stats"><Stat title="Total Books" value={books.reduce((a,b)=>a+b.total,0)} sub="All copies" icon={Library}/><Stat title="Available" value={books.reduce((a,b)=>a+b.available,0)} sub="Ready to issue" icon={CheckCircle2}/><Stat title={canManage?"Issued Books":"My Books"} value={canManage?books.filter(b=>b.issuedTo).length:myBooks.length} sub={canManage?"Currently borrowed":"Currently borrowed"} icon={BookOpen}/></div>
 <div className="card"><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search story, subject, activity or author..."/><select value={cat} onChange={e=>setCat(e.target.value)}><option>All</option>{[...new Set(books.map(b=>b.category))].map(c=><option key={c}>{c}</option>)}</select></div>
 <table><thead><tr><th>Book</th><th>Author</th><th>Category</th><th>Age Group</th><th>Copies</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map(b=><tr key={b.id}><td><b>{b.title}</b></td><td>{b.author}</td><td>{b.category}</td><td>{b.ageGroup||"Primary"}</td><td>{b.available} / {b.total}</td><td><span className={b.available>0?"present":"pending"}>{b.available>0?"Available":"Not Available"}</span></td><td>{canManage?(b.issuedTo?<button type="button" className="link" onClick={()=>returnBook(b.id)}>Return</button>:<button type="button" className="link" onClick={()=>issue(b.id)}>Issue</button>):<button type="button" className="link" disabled={b.available<1||b.issuedTo===studentName} onClick={()=>issue(b.id)}>{b.issuedTo===studentName?"Borrowed":"Borrow"}</button>}</td></tr>)}</tbody></table></div>
 {studentName&&<div className="card" style={{marginTop:18}}><div className="card-head"><h3>My Borrowed Books</h3><span className="pill">{studentName}</span></div>{myBooks.length?myBooks.map(b=><div className="activity" key={b.id}><span className="dot"></span><div><b>{b.title}</b><small>Due {b.due}</small></div><span className="pending">Issued</span></div>):<p className="muted">No books borrowed yet.</p>}</div>}
 {open&&<LibraryForm onClose={()=>setOpen(false)} onSave={addBook}/>}</>;
}
function LibraryForm({onClose,onSave}){const [title,setTitle]=useState(""),[author,setAuthor]=useState(""),[category,setCategory]=useState("Story"),[ageGroup,setAgeGroup]=useState("6–10 Years"),[total,setTotal]=useState(1);return <Modal title="Add Primary School Book" onClose={onClose}><form className="formgrid" onSubmit={e=>{e.preventDefault();if(!title.trim()||!author.trim())return;onSave({title:title.trim(),author:author.trim(),category,ageGroup,total:Number(total),available:Number(total),issuedTo:"",due:""})}}><label>Book Title<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Charlotte's Web"/></label><label>Author<input required value={author} onChange={e=>setAuthor(e.target.value)} placeholder="Author name"/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option>Story</option><option>Mathematics</option><option>EVS</option><option>Tamil</option><option>Life Skills</option><option>Activity</option></select></label><label>Age Group<select value={ageGroup} onChange={e=>setAgeGroup(e.target.value)}><option>5–8 Years</option><option>6–10 Years</option><option>7–11 Years</option><option>8–12 Years</option></select></label><label>Total Copies<input type="number" min="1" value={total} onChange={e=>setTotal(e.target.value)}/></label><button className="primary">Add Book</button></form></Modal>}

export {LibraryPage,LibraryForm};
