import React,{useState} from "react";
import {School} from "lucide-react";
import {PageTools} from "../components/ui";
import {accounts,teacherAccounts} from "../data/seed";
import {load,save} from "../utils/storage";

function UsersPage({s}){const [users,setUsers]=useState(()=>load("bf_users",[accounts.admin,...teacherAccounts]));const add=()=>{const name=prompt("New user name:");if(!name)return;const next=[...users,{name,email:name.toLowerCase().replaceAll(" ",".")+"@school.demo",role:"Teacher"}];setUsers(next);save("bf_users",next);s.notify("User added successfully")};return <><PageTools title="User Management" sub="Demo login accounts and role access." action={add} actionText="＋ Add User"/><div className="card"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th></tr></thead><tbody>{users.map(a=><tr key={a.email}><td><b>{a.name}</b></td><td>{a.email}</td><td><span className="pill">{a.role}</span></td><td><span className="present">Active</span></td></tr>)}</tbody></table></div></>}
function Reports({s}){const exportReport=()=>{const data=["Bright Future Primary School Report","Students: "+s.students.length,"Teachers: "+s.teachers.length,"Homework: "+s.homeworkItems.length,"Notices: "+s.notices.length].join("\n");const blob=new Blob([data],{type:"text/plain"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="school-report.txt";a.click();URL.revokeObjectURL(a.href);s.notify("Report exported")};return <><PageTools title="Reports" sub="Quick school performance reports." action={exportReport} actionText="Export Report"/><div className="report-grid">{[["Student Strength",s.students.length,"Active records"],["Attendance","94.6%","School average"],["Academic Average","88.4%","Unit Test 1"],["Fee Collection","82%","Monthly target"]].map(x=><div className="report-box" key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong><span>{x[2]}</span><div className="bar"><i style={{width:"78%"}}></i></div></div>)}</div></>}
function SettingsPage({s}){const [name,setName]=useState(()=>load("bf_school_name","Bright Future Primary School"));return <><PageTools title="Settings" sub="School profile and preferences." action={()=>{save("bf_school_name",name);s.notify("Settings saved successfully")}} actionText="Save Changes"/><div className="card formgrid"><label>School Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Academic Year<input defaultValue="2026 – 2027"/></label><label>School Phone<input defaultValue="+91 98765 43210"/></label><label>Email<input defaultValue="office@brightfuture.demo"/></label></div></>}
function Leave({s}){const [requests,setRequests]=useState(()=>load("bf_leave",[]));const request=()=>{const next=[...requests,{type:"Casual Leave",date:"Sep 18",reason:"Personal work",status:"Pending"}];setRequests(next);save("bf_leave",next);s.notify("Leave request submitted successfully")};return <><PageTools title="Leave Request" sub="Submit and track your leave requests." action={request} actionText="＋ Request Leave"/><div className="card"><table><thead><tr><th>Type</th><th>Dates</th><th>Reason</th><th>Status</th></tr></thead><tbody>{requests.length?requests.map((x,i)=><tr key={i}><td>{x.type}</td><td>{x.date}</td><td>{x.reason}</td><td><span className="pending">{x.status}</span></td></tr>):<tr><td colSpan="4">No leave requests yet. Click Request Leave to add one.</td></tr>}</tbody></table></div></>}
function Profile({u,s}){const [name,setName]=useState(u.name);return <><div className="profile-card"><div className="avatar huge">{name[0]}</div><h1>{name}</h1><p>{u.role} · Bright Future Primary School</p><div className="details"><span>Email <b>{u.email}</b></span><span>Role <b>{u.role}</b></span><span>Phone <b>+91 98765 43210</b></span></div><button type="button" className="primary" onClick={()=>s.notify("Profile saved for "+name)}>Save Profile</button><button type="button" className="secondary" onClick={()=>{const n=prompt("Enter display name",name);if(n){setName(n);s.notify("Profile name updated")}}}>Edit Profile</button></div></>}

export {UsersPage,Reports,SettingsPage,Leave,Profile};
