import React,{useEffect,useState} from "react";
import {Users,GraduationCap,FileText,Wallet,Search,UserRound,Trash2,Download,TrendingUp,TrendingDown} from "lucide-react";
import {Modal,PageTools,Stat} from "../components/ui";
import {fmt,todayISO} from "../utils/format";
import {load,save} from "../utils/storage";

const staffRoles=["Teacher","Principal","Office Staff","Accountant","Driver","Helper","Security","Cleaner"];
const initialStaff=[
 {id:1,name:"Priya Sharma",role:"Teacher",dept:"Mathematics",joined:"2019-06-01",phone:"98400 44001",basic:32000,hra:8000,allow:3000,pf:3840,tax:1500,bank:"SBI ····4521",status:"Active"},
 {id:2,name:"Meena Joseph",role:"Teacher",dept:"English",joined:"2020-06-01",phone:"98400 44002",basic:30000,hra:7500,allow:3000,pf:3600,tax:1200,bank:"HDFC ····8830",status:"Active"},
 {id:3,name:"Arun Kumar",role:"Teacher",dept:"EVS",joined:"2021-06-01",phone:"98400 44003",basic:28000,hra:7000,allow:2500,pf:3360,tax:1000,bank:"ICICI ····1207",status:"Active"},
 {id:4,name:"Kavitha R",role:"Teacher",dept:"Tamil",joined:"2018-06-01",phone:"98400 44004",basic:31000,hra:7750,allow:3000,pf:3720,tax:1300,bank:"SBI ····9034",status:"Active"},
 {id:5,name:"Lakshmi N",role:"Principal",dept:"Administration",joined:"2015-04-01",phone:"98400 44005",basic:60000,hra:15000,allow:8000,pf:7200,tax:6500,bank:"SBI ····2211",status:"Active"},
 {id:6,name:"Ganesh P",role:"Accountant",dept:"Office",joined:"2020-01-15",phone:"98400 44006",basic:22000,hra:5500,allow:2000,pf:2640,tax:500,bank:"IOB ····5578",status:"Active"},
 {id:7,name:"Suresh Kumar",role:"Driver",dept:"Transport",joined:"2019-08-01",phone:"98400 33001",basic:16000,hra:4000,allow:2500,pf:1920,tax:0,bank:"Canara ····6642",status:"Active"},
 {id:8,name:"Selvi M",role:"Helper",dept:"Primary Block",joined:"2022-06-01",phone:"98400 44008",basic:12000,hra:3000,allow:1000,pf:1440,tax:0,bank:"IOB ····7710",status:"Active"},
 {id:9,name:"Murugan K",role:"Security",dept:"Main Gate",joined:"2021-03-01",phone:"98400 44009",basic:13000,hra:3250,allow:1500,pf:1560,tax:0,bank:"SBI ····3390",status:"On Leave"}
];
const grossOf=e=>e.basic+e.hra+e.allow;const netOf=e=>grossOf(e)-e.pf-e.tax;
function Payroll({s}){
 const [staff,setStaff]=useState(()=>load("bf_staff_v1",initialStaff));useEffect(()=>save("bf_staff_v1",staff),[staff]);
 const [runs,setRuns]=useState(()=>load("bf_payroll_runs_v1",[{month:"2026-08",paid:9,total:279640,date:"2026-09-01"}]));useEffect(()=>save("bf_payroll_runs_v1",runs),[runs]);
 const [tab,setTab]=useState("staff");const [month,setMonth]=useState(todayISO().slice(0,7));const [q,setQ]=useState("");const [role,setRole]=useState("All");
 const [lop,setLop]=useState({});
 const list=staff.filter(e=>(role==="All"||e.role===role)&&(e.name+e.dept+e.role).toLowerCase().includes(q.toLowerCase()));
 const active=staff.filter(e=>e.status==="Active");
 const slip=e=>{const days=Number(lop[e.id]||0);const lopAmt=Math.round(grossOf(e)/30*days);return {gross:grossOf(e),lop:lopAmt,ded:e.pf+e.tax+lopAmt,net:netOf(e)-lopAmt,days}};
 const totals=active.reduce((a,e)=>{const x=slip(e);return {gross:a.gross+x.gross,ded:a.ded+x.ded,net:a.net+x.net}},{gross:0,ded:0,net:0});
 const alreadyRun=runs.some(r=>r.month===month);
 const runPayroll=()=>{if(alreadyRun)return s.notify("Payroll for "+month+" already processed");if(!confirm(`Process salary for ${active.length} staff · Net ${fmt(totals.net)}?`))return;setRuns([{month,paid:active.length,total:totals.net,date:todayISO()},...runs]);const fin=load("bf_finance_v1",[]);save("bf_finance_v1",[{id:Date.now(),type:"expense",category:"Salaries",desc:"Payroll "+month+" · "+active.length+" staff",amount:totals.net,date:todayISO(),by:"School Admin"},...fin]);s.notify("✓ Payroll processed · "+fmt(totals.net)+" credited to "+active.length+" accounts · posted to Finance")};
 const add=()=>s.setModal(<StaffForm s={s} onClose={()=>s.setModal(null)} onSave={e=>{setStaff([...staff,{...e,id:Date.now()}]);s.setModal(null);s.notify("Staff added")}}/>);
 const edit=e=>s.setModal(<StaffForm s={s} existing={e} onClose={()=>s.setModal(null)} onSave={n=>{setStaff(staff.map(x=>x.id===e.id?{...x,...n}:x));s.setModal(null);s.notify("Staff updated")}}/>);
 const toggleStatus=id=>setStaff(staff.map(e=>e.id===id?{...e,status:e.status==="Active"?"On Leave":"Active"}:e));
 const byRole=staffRoles.map(r=>[r,staff.filter(e=>e.role===r).length]).filter(x=>x[1]);
 return <><PageTools title="Staff Management & Payroll" sub="Staff records, salary structure, monthly payroll and payslips." action={tab==="staff"?add:runPayroll} actionText={tab==="staff"?"Add Staff":alreadyRun?"Payroll Done":"Run Payroll"}/>
 <div className="tabs">{[["staff","Staff Directory"],["payroll","Monthly Payroll"],["history","Payroll History"]].map(([k,l])=><button type="button" key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{l}</button>)}</div>
 <div className="stats"><Stat title="Total Staff" value={staff.length} sub={active.length+" active · "+(staff.length-active.length)+" on leave"} icon={Users}/><Stat title="Teaching" value={staff.filter(e=>e.role==="Teacher").length} sub="Teachers" icon={GraduationCap}/><Stat title="Non-teaching" value={staff.filter(e=>e.role!=="Teacher").length} sub="Support staff" icon={UserRound}/><Stat title="Monthly Salary Bill" value={fmt(totals.net)} sub={"Net payable · "+month} icon={Wallet}/></div>
 {tab==="staff"&&<div className="card"><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search staff by name, role or department..."/><select value={role} onChange={e=>setRole(e.target.value)}><option>All</option>{staffRoles.map(r=><option key={r}>{r}</option>)}</select></div>
  <div className="head-picker">{byRole.map(([r,n])=><span key={r} className="head-chip on" style={{cursor:"default"}}>{r}<b>{n}</b></span>)}</div>
  <table><thead><tr><th>Staff</th><th>Role</th><th>Department</th><th>Joined</th><th>Basic</th><th>Gross</th><th>Net Salary</th><th>Status</th><th>Action</th></tr></thead><tbody>{list.map(e=><tr key={e.id}><td><div style={{display:"flex",gap:10,alignItems:"center"}}><span className="avatar" style={{width:30,height:30,fontSize:12}}>{e.name[0]}</span><div><b>{e.name}</b><br/><small className="muted">{e.phone}</small></div></div></td><td><span className="pill">{e.role}</span></td><td>{e.dept}</td><td>{e.joined}</td><td>{fmt(e.basic)}</td><td>{fmt(grossOf(e))}</td><td><b>{fmt(netOf(e))}</b></td><td><button type="button" className={e.status==="Active"?"present":"pending"} onClick={()=>toggleStatus(e.id)}>{e.status}</button></td><td><button type="button" className="link" onClick={()=>edit(e)}>Edit</button> <button type="button" className="link" onClick={()=>{if(confirm("Remove "+e.name+"?")){setStaff(staff.filter(x=>x.id!==e.id));s.notify("Staff removed")}}}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>}
 {tab==="payroll"&&<><div className="card" style={{marginBottom:18}}><div className="card-head"><h3>Payroll for <input type="month" value={month} onChange={e=>setMonth(e.target.value)} style={{border:"1px solid #e1e4ec",borderRadius:8,padding:"6px 10px",marginLeft:8}}/></h3>{alreadyRun?<span className="present">Processed</span>:<span className="pending">Pending</span>}</div>
  <div className="pn"><div className="pn-col pos"><h4><TrendingUp size={15}/> Earnings</h4><strong>{fmt(totals.gross)}</strong><div className="pn-row"><span>Basic</span><b>{fmt(active.reduce((a,e)=>a+e.basic,0))}</b></div><div className="pn-row"><span>HRA</span><b>{fmt(active.reduce((a,e)=>a+e.hra,0))}</b></div><div className="pn-row"><span>Allowances</span><b>{fmt(active.reduce((a,e)=>a+e.allow,0))}</b></div></div><div className="pn-col neg"><h4><TrendingDown size={15}/> Deductions</h4><strong>{fmt(totals.ded)}</strong><div className="pn-row"><span>PF (12%)</span><b>{fmt(active.reduce((a,e)=>a+e.pf,0))}</b></div><div className="pn-row"><span>Professional Tax / TDS</span><b>{fmt(active.reduce((a,e)=>a+e.tax,0))}</b></div><div className="pn-row"><span>Loss of Pay</span><b>{fmt(active.reduce((a,e)=>a+slip(e).lop,0))}</b></div></div></div>
  <div className="net-bar pos"><span>Net Payable</span><b>{fmt(totals.net)}</b><small>{active.length} active staff</small></div></div>
  <div className="card"><table><thead><tr><th>Staff</th><th>Role</th><th>Basic</th><th>HRA</th><th>Allow.</th><th>Gross</th><th>PF</th><th>Tax</th><th>LOP Days</th><th>Net Pay</th><th>Payslip</th></tr></thead><tbody>{active.map(e=>{const x=slip(e);return <tr key={e.id}><td><b>{e.name}</b><br/><small className="muted">{e.bank}</small></td><td>{e.role}</td><td>{fmt(e.basic)}</td><td>{fmt(e.hra)}</td><td>{fmt(e.allow)}</td><td>{fmt(x.gross)}</td><td className="txt-neg">{fmt(e.pf)}</td><td className="txt-neg">{fmt(e.tax)}</td><td><input type="number" min="0" max="30" className="inline" style={{width:60,border:"1px solid #e1e4ec"}} value={lop[e.id]||0} onChange={ev=>setLop({...lop,[e.id]:ev.target.value})}/></td><td><b className="txt-pos">{fmt(x.net)}</b></td><td><button type="button" className="link" onClick={()=>s.setModal(<Payslip e={e} x={x} month={month} onClose={()=>s.setModal(null)}/>)}><FileText size={14}/> View</button></td></tr>})}</tbody><tfoot><tr><td colSpan={5}><b>Total</b></td><td><b>{fmt(totals.gross)}</b></td><td colSpan={3} className="txt-neg"><b>− {fmt(totals.ded)}</b></td><td><b className="txt-pos">{fmt(totals.net)}</b></td><td></td></tr></tfoot></table></div></>}
 {tab==="history"&&<div className="card">{runs.length===0&&<p className="muted">No payroll runs yet.</p>}<table><thead><tr><th>Month</th><th>Processed On</th><th>Staff Paid</th><th>Total Net</th><th>Status</th><th></th></tr></thead><tbody>{runs.map(r=><tr key={r.month}><td><b>{r.month}</b></td><td>{r.date}</td><td>{r.paid}</td><td><b>{fmt(r.total)}</b></td><td><span className="present">Credited</span></td><td><button type="button" className="link" onClick={()=>s.notify("Bank advice for "+r.month+" downloaded")}><Download size={14}/> Bank Advice</button></td></tr>)}</tbody></table></div>}
 </>}
function Payslip({e,x,month,onClose}){return <Modal title={"Payslip · "+month} onClose={onClose}><div className="payslip"><div className="ps-head"><div><b>Bright Future Primary School</b><small>Coimbatore, Tamil Nadu</small></div><div style={{textAlign:"right"}}><b>{e.name}</b><small>{e.role} · {e.dept}</small><small>{e.bank}</small></div></div><div className="pn"><div className="pn-col pos"><h4>Earnings</h4><div className="pn-row"><span>Basic</span><b>{fmt(e.basic)}</b></div><div className="pn-row"><span>HRA</span><b>{fmt(e.hra)}</b></div><div className="pn-row"><span>Allowances</span><b>{fmt(e.allow)}</b></div><div className="pn-row"><span><b>Gross</b></span><b>{fmt(x.gross)}</b></div></div><div className="pn-col neg"><h4>Deductions</h4><div className="pn-row"><span>PF</span><b>{fmt(e.pf)}</b></div><div className="pn-row"><span>Tax</span><b>{fmt(e.tax)}</b></div><div className="pn-row"><span>LOP ({x.days} days)</span><b>{fmt(x.lop)}</b></div><div className="pn-row"><span><b>Total</b></span><b>{fmt(x.ded)}</b></div></div></div><div className="net-bar pos"><span>Net Pay</span><b>{fmt(x.net)}</b></div><button type="button" className="primary full" onClick={()=>window.print()}><Download size={16}/> Download / Print</button></div></Modal>}
function StaffForm({s,existing,onSave,onClose}){const [f,setF]=useState(existing||{name:"",role:"Teacher",dept:"",joined:todayISO(),phone:"",basic:20000,hra:5000,allow:2000,pf:2400,tax:0,bank:"",status:"Active"});const set=k=>e=>setF({...f,[k]:e.target.value});const num=k=>e=>setF({...f,[k]:Number(e.target.value)});return <Modal title={existing?"Edit Staff":"Add Staff"} onClose={onClose}><div className="formgrid"><label>Name<input value={f.name} onChange={set("name")}/></label><label>Role<select value={f.role} onChange={set("role")}>{staffRoles.map(r=><option key={r}>{r}</option>)}</select></label><label>Department<input value={f.dept} onChange={set("dept")}/></label><label>Phone<input value={f.phone} onChange={set("phone")}/></label><label>Joining Date<input type="date" value={f.joined} onChange={set("joined")}/></label><label>Bank A/c<input value={f.bank} onChange={set("bank")} placeholder="SBI ····1234"/></label><label>Basic (₹)<input type="number" value={f.basic} onChange={e=>setF({...f,basic:Number(e.target.value),hra:Math.round(Number(e.target.value)*0.25),pf:Math.round(Number(e.target.value)*0.12)})}/></label><label>HRA (₹)<input type="number" value={f.hra} onChange={num("hra")}/></label><label>Allowances (₹)<input type="number" value={f.allow} onChange={num("allow")}/></label><label>PF (₹)<input type="number" value={f.pf} onChange={num("pf")}/></label><label>Tax (₹)<input type="number" value={f.tax} onChange={num("tax")}/></label></div><div className="bill"><div><span>Gross</span><b>{fmt(grossOf(f))}</b></div><div className="total"><span>Net Salary</span><b>{fmt(netOf(f))}</b></div></div><button type="button" className="primary full" onClick={()=>{if(!f.name)return s.notify("Name required");onSave(f)}}>{existing?"Save":"Add Staff"}</button></Modal>}

export {staffRoles,initialStaff,grossOf,netOf,Payroll,Payslip,StaffForm};
