import React,{useState} from "react";
import {Send,RefreshCw,AlertTriangle} from "lucide-react";
import {Activity,Card,Modal,PageTools} from "../components/ui";
import {defaultTT} from "../data/seed";

function ReportUnavailability({u,s}){
 const teacher=s.teachers.find(t=>t.name===u.name)||s.teachers[0];
 const [day,setDay]=useState("Today"),[reason,setReason]=useState("Health issue / emergency"),[note,setNote]=useState("");
 const periods=defaultTT.filter(x=>x[0]==="Monday"&&x[3]===teacher.name).map(x=>({time:x[1],subject:x[2]}));
 const [selected,setSelected]=useState(()=>periods.length?[periods[periods.length-1].time]:[]);
 const toggle=p=>setSelected(v=>v.includes(p)?v.filter(x=>x!==p):[...v,p]);
 const submit=e=>{e.preventDefault();if(!selected.length)return s.notify("Select at least one affected period");const items=selected.map(time=>{const row=defaultTT.find(x=>x[0]==="Monday"&&x[1]===time&&x[3]===teacher.name);return {period:time,subject:row?.[2]||teacher.subject,classes:(teacher.classes||"").split(" / ")[0]}});const req={id:Date.now(),teacher:teacher.name,day,reason,note:note.trim(),items,status:"Pending",createdAt:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})};s.setAvailabilityRequests([...s.availabilityRequests,req]);s.notify("Unavailability request sent to Admin");setNote("");setSelected([])};
 const mine=s.availabilityRequests.filter(x=>x.teacher===u.name);
 return <><PageTools title="Report Unavailability" sub="Tell the Admin when you are suddenly unavailable. The Admin will arrange the substitute."/><div className="tt-banner">📩 <b>Teacher → Admin:</b> submit the affected periods here. You do not assign another teacher yourself.</div><div className="grid2"><Card title="New Unavailability Request"><form className="formgrid" onSubmit={submit}><label>Date / Day<select value={day} onChange={e=>setDay(e.target.value)}><option>Today</option><option>Tomorrow</option><option>Wednesday</option><option>Thursday</option><option>Friday</option></select></label><label>Reason<select value={reason} onChange={e=>setReason(e.target.value)}><option>Health issue / emergency</option><option>Staff meeting</option><option>Half-day leave</option><option>Personal work</option></select></label><label>Affected periods<div className="period-picks">{periods.length?periods.map(x=><button type="button" key={x.time} className={selected.includes(x.time)?"status present":"status"} onClick={()=>toggle(x.time)}>{x.time} · {x.subject}</button>):<span className="muted">No timetable periods found for this teacher.</span>}</div></label><label>Note (optional)<textarea rows="3" value={note} onChange={e=>setNote(e.target.value)} placeholder="Example: I am unavailable for the afternoon class."/></label><button className="primary"><Send size={16}/> Send to Admin</button></form></Card><Card title="What happens next"><Activity text="Request reaches Admin" time="Pending approval"/><Activity text="Admin checks affected classes" time="Date + period + subject"/><Activity text="ERP finds available teacher" time="Free period + subject priority"/><Activity text="Substitute gets duty notification" time="Teacher portal"/></Card></div><div className="card"><div className="card-head"><h3>My Requests</h3><span className="pill">{mine.length} submitted</span></div>{mine.length?<table><thead><tr><th>Date</th><th>Affected Periods</th><th>Reason</th><th>Status</th></tr></thead><tbody>{mine.map(x=><tr key={x.id}><td>{x.day}</td><td>{x.items.map(i=>i.period).join(", ")}</td><td>{x.reason}</td><td><span className={x.status==="Assigned"?"present":"pill"}>{x.status}</span></td></tr>)}</tbody></table>:<div className="chat-empty"><div>📩</div><b>No requests yet</b><span>Your submitted unavailability requests will appear here.</span></div>}</div></>;
}

function StaffRequests({s}){
 const pending=s.availabilityRequests.filter(x=>x.status==="Pending");
 const findBest=(req,item)=>{const original=s.teachers.find(t=>t.name===req.teacher)||s.teachers[0];const candidates=s.teachers.filter(t=>t.name!==req.teacher).map(t=>{const busy=s.substitutions.some(x=>x.substitute===t.name&&x.day===req.day&&x.period===item.period);const subjectMatch=t.subject===item.subject||t.subject.split(" / ").includes(item.subject);return {...t,busy,subjectMatch}}).sort((a,b)=>Number(b.subjectMatch)-Number(a.subjectMatch)||Number(a.busy)-Number(b.busy));return candidates.find(t=>!t.busy)||candidates[0]};
 const assign=req=>{const newItems=req.items.map(item=>{const best=findBest(req,item);return best?{id:Date.now()+Math.random(),day:req.day,period:item.period,original:req.teacher,subject:item.subject,classes:item.classes,reason:req.reason,substitute:best.name,status:"Assigned"}:null}).filter(Boolean);if(!newItems.length)return s.notify("No available substitute found");const next=[...s.substitutions,...newItems];s.setSubstitutions(next);s.setAvailabilityRequests(s.availabilityRequests.map(x=>x.id===req.id?{...x,status:"Assigned",assignedIds:newItems.map(i=>i.id)}:x));s.notify(`${newItems.map(x=>x.substitute).join(", ")} assigned and notified`)};
 const reject=req=>{s.setAvailabilityRequests(s.availabilityRequests.map(x=>x.id===req.id?{...x,status:"Rejected"}:x));s.notify("Request marked as rejected")};
 return <><PageTools title="Staff Requests" sub="Review teacher unavailability reports and arrange cover before assigning a substitute."/><div className="tt-banner">🔔 <b>Admin action:</b> teacher reports first → Admin reviews → Auto Find Substitute → assignment appears on the substitute teacher portal.</div><div className="grid2"><Card title="Request Summary"><div className="details"><span>Pending<b>{pending.length}</b></span><span>Assigned<b>{s.availabilityRequests.filter(x=>x.status==="Assigned").length}</b></span><span>Total Requests<b>{s.availabilityRequests.length}</b></span><span>Substitutions<b>{s.substitutions.length}</b></span></div></Card><Card title="Admin Workflow"><Activity text="1. Receive teacher request" time="Teacher portal"/><Activity text="2. Review affected period" time="Class + subject"/><Activity text="3. Auto Find Substitute" time="Free-period priority"/><Activity text="4. Assign & notify" time="Teacher portal"/></Card></div><div className="card"><div className="card-head"><h3>Unavailability Requests</h3><span className="pill">{pending.length} pending</span></div>{s.availabilityRequests.length?<table><thead><tr><th>Teacher</th><th>Date</th><th>Affected Classes</th><th>Reason</th><th>Status / Action</th></tr></thead><tbody>{s.availabilityRequests.map(req=><tr key={req.id}><td><b>{req.teacher}</b></td><td>{req.day}</td><td>{req.items.map(i=><div key={i.period}>{i.period} · {i.classes} · {i.subject}</div>)}</td><td>{req.reason}{req.note&&<div className="muted">{req.note}</div>}</td><td>{req.status==="Pending"?<div className="row-actions"><button type="button" className="primary" onClick={()=>assign(req)}><RefreshCw size={15}/> Auto Find & Assign</button><button type="button" className="status" onClick={()=>reject(req)}>Reject</button></div>:<span className="present">{req.status}</span>}</td></tr>)}</tbody></table>:<div className="chat-empty"><div>🔔</div><b>No staff requests</b><span>When a teacher reports unavailability, the request will appear here.</span></div>}</div></>;
}

function SubstitutionPlanner({s}){
 const [teacher,setTeacher]=useState("Priya Sharma"),[period,setPeriod]=useState("02:00 PM"),[day,setDay]=useState("Today"),[reason,setReason]=useState("Health issue / emergency"),[open,setOpen]=useState(false);
 const active=s.teachers.find(t=>t.name===teacher)||s.teachers[0];
 const candidates=s.teachers.filter(t=>t.name!==teacher).map(t=>{const busy=s.substitutions.some(x=>x.substitute===t.name&&x.day===day&&x.period===period);const subjectMatch=t.subject.split(" /").some(v=>v===active.subject)||t.subject===active.subject;return {...t,busy,subjectMatch}}).sort((a,b)=>Number(b.subjectMatch)-Number(a.subjectMatch)||Number(a.busy)-Number(b.busy));
 const best=candidates.find(t=>!t.busy)||candidates[0];
 const create=()=>{if(!best)return;const item={id:Date.now(),day,period,original:teacher,subject:active.subject,classes:active.classes.split(" / ")[0],reason,substitute:best.name,status:"Assigned"};s.setSubstitutions([...s.substitutions,item]);s.notify(`Auto-assigned ${best.name} for ${active.subject}`);setOpen(false)};
 return <><PageTools title="Staff Substitution" sub="Admin can also manually arrange cover for exceptional cases." action={()=>setOpen(true)} actionText="＋ Manual Arrange"/><div className="tt-banner">🤖 <b>Smart Substitute Planner:</b> normal flow starts with a teacher request. This page is an Admin fallback for urgent cases.</div><div className="card"><div className="card-head"><h3>Substitution Schedule</h3><span className="pill">{s.substitutions.length} assignments</span></div>{s.substitutions.length?<table><thead><tr><th>Period</th><th>Original Teacher</th><th>Class / Subject</th><th>Reason</th><th>Substitute</th><th>Status</th></tr></thead><tbody>{s.substitutions.map(x=><tr key={x.id}><td>{x.day} · {x.period}</td><td><b>{x.original}</b></td><td>{x.classes} · {x.subject}</td><td>{x.reason}</td><td><b>{x.substitute}</b></td><td><span className="present">{x.status}</span></td></tr>)}</tbody></table>:<div className="chat-empty"><div>🔄</div><b>No substitutions scheduled</b><span>Teacher requests will create assignments here after Admin approval.</span></div>}</div>{open&&<Modal title="Manual Emergency Substitute" onClose={()=>setOpen(false)}><form className="formgrid" onSubmit={e=>{e.preventDefault();create()}}><label>Unavailable Teacher<select value={teacher} onChange={e=>setTeacher(e.target.value)}>{s.teachers.map(t=><option key={t.name}>{t.name}</option>)}</select></label><label>Period<select value={period} onChange={e=>setPeriod(e.target.value)}><option>01:00 PM</option><option>02:00 PM</option><option>02:45 PM</option><option>03:30 PM</option></select></label><label>Date / Day<select value={day} onChange={e=>setDay(e.target.value)}><option>Today</option><option>Tomorrow</option></select></label><label>Reason<select value={reason} onChange={e=>setReason(e.target.value)}><option>Health issue / emergency</option><option>Staff meeting</option><option>Half-day leave</option><option>Personal work</option></select></label><div className="substitute-preview"><AlertTriangle size={18}/><div><b>Automatic recommendation</b><span>{best?`${best.name} · ${best.subject} · ${best.busy?"May have a conflict":"Free period"}`:"No available teacher"}</span></div></div><button className="primary" disabled={!best}><RefreshCw size={16}/> Auto Assign & Notify</button></form></Modal>}</>}
function SubstitutionDuty({u,s}){const duties=s.substitutions.filter(x=>x.substitute===u.name);return <><PageTools title="Substitution Duty" sub="Classes assigned to you when another teacher is unavailable."/><div className="tt-banner">🔔 <b>Teacher notification:</b> substitution duties are added separately from your regular timetable.</div>{duties.length?<div className="homework-grid">{duties.map(x=><div className="card" key={x.id}><span className="pill">{x.status}</span><h3>{x.subject} · {x.classes}</h3><p>{x.day} · {x.period}</p><p className="muted">Original teacher: {x.original}</p><p className="muted">Reason: {x.reason}</p><button type="button" className="primary" onClick={()=>s.notify(`Opening ${x.classes} substitution class`)}>Open Class</button></div>)}</div>:<div className="card"><div className="chat-empty"><div>✓</div><b>No substitution duty</b><span>You have no extra class assigned at the moment.</span></div></div>}</>}

export {ReportUnavailability,StaffRequests,SubstitutionPlanner,SubstitutionDuty};
