import React,{useState} from "react";
import {CheckCircle2} from "lucide-react";
import {Modal,PageTools} from "../components/ui";
import {defaultTT} from "../data/seed";
import {load,save} from "../utils/storage";

function Timetable({role,u,s}){const [rows,setRows]=useState(()=>load("bf_timetable_v2",defaultTT));const [open,setOpen]=useState(false);const saveRows=r=>{setRows(r);save("bf_timetable_v2",r)};let shown=role==="Teacher"?rows.filter(x=>x[3]===u?.name):rows;return <><PageTools title={role==="Admin"?"Timetable & Teacher Assignment":"My Timetable"} sub="Assignments are shared across portals." action={role==="Admin"?()=>setOpen(true):null} actionText="＋ Assign Period"/><div className="card"><div className="tt-banner">🔗 <b>Connected timetable:</b> changes are saved in this browser and visible to the relevant portals.</div><table><thead><tr><th>Day</th><th>Time</th><th>Subject</th><th>Teacher</th><th>Class</th><th>Action</th></tr></thead><tbody>{shown.map((x,i)=><tr key={i}><td><b>{x[0]}</b></td><td>{x[1]}</td><td>{x[2]}</td><td>{x[3]}</td><td>Grade 3-A</td><td><button type="button" className="iconbtn" onClick={()=>s.notify("Period is active: "+x[2])}><CheckCircle2 size={16}/></button></td></tr>)}</tbody></table></div>{open&&<PeriodForm teachers={s.teachers} onClose={()=>setOpen(false)} onSave={r=>{saveRows([...rows,r]);s.notify("Period assigned successfully");setOpen(false)}}/>}</>}
function PeriodForm({teachers,onClose,onSave}){const [day,setDay]=useState("Monday"),[time,setTime]=useState("12:15 PM"),[subject,setSubject]=useState("Mathematics"),[teacher,setTeacher]=useState(teachers[0]?.name||"");return <Modal title="Assign Period" onClose={onClose}><form className="formgrid" onSubmit={e=>{e.preventDefault();onSave([day,time,subject,teacher])}}><label>Day<select value={day} onChange={e=>setDay(e.target.value)}>{["Monday","Tuesday","Wednesday","Thursday","Friday"].map(x=><option key={x}>{x}</option>)}</select></label><label>Time<input value={time} onChange={e=>setTime(e.target.value)}/></label><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>Teacher<select value={teacher} onChange={e=>setTeacher(e.target.value)}>{teachers.map(t=><option key={t.name}>{t.name}</option>)}</select></label><button className="primary">Save Period</button></form></Modal>}

export {Timetable,PeriodForm};
